# Classes and Objects

In [1]:
class Guru:
    a=100
    print("My name is guru")
    

My name is guru


In [6]:
class parent:
    v1 = 100
class addfun:
    def additionOperatio(a,b):
        c= a+b
        return c
    print(additionOperatio(10,10))
    print(parent().v1)

20
100


In [17]:
# using self
class Guru:
    def __init__(self,a,b):
        self.a=a
        self.b=b
obj = Guru(10,10)
print(obj.a)        

10


In [28]:
import hello
print(hello.funstuff.hf())

# file Operation

In [31]:
#write a file
file=open("fun.txt","w")
file.write("Hello")

5

In [30]:
#read a file
file=open("fun.txt","r")
print(file.read())

Hello


In [48]:
#read a file with count of words
file=open("myfile.txt","r")
robj = file.read().split()
#print(robj)
myset = sorted(set(robj))
for word in myset:
    print("{0} ---> {1}".format(word,robj.count(word)))

"deployment" ---> 2
2017. ---> 1
Actually, ---> 1
Also, ---> 1
As ---> 1
Bottle, ---> 1
But ---> 1
But, ---> 3
By ---> 1
Dec ---> 1
Django ---> 4
Django! ---> 1
Django, ---> 2
Django2.0 ---> 2
Flask, ---> 1
Hellon ---> 1
It ---> 1
Just ---> 1
MVC, ---> 1
Now ---> 1
ORM, ---> 1
OS, ---> 1
Ppython ---> 1
Pyramid, ---> 1
Python ---> 4
Python, ---> 2
Python. ---> 1
Python2 ---> 1
Python3 ---> 1
Python3.0, ---> 1
The ---> 2
These ---> 1
To ---> 1
US ---> 1
With ---> 1
a ---> 4
about ---> 1
also ---> 1
among ---> 1
and ---> 2
application ---> 5
application. ---> 1
are ---> 1
as ---> 1
be ---> 2
because ---> 1
bothering ---> 1
build ---> 1
can ---> 3
cause ---> 1
code ---> 1
data ---> 1
databases. ---> 1
dependencies, ---> 1
develop ---> 2
does ---> 1
easily ---> 1
errors ---> 1
etc. ---> 3
famous ---> 1
feedbacks ---> 1
following ---> 2
for ---> 2
framework ---> 2
frameworks ---> 1
friends ---> 1
from ---> 2
frustrates ---> 1
frustrating. ---> 1
full ---> 1
generator, ---> 1
getting ---> 1
g

In [67]:
file=open("myfile.txt","r")
var = file.read()
var = var.replace(".","")
var = var.replace(",","")
words = var.split()
#words = ['' if i in '.' else i for i in mywords]
def countWords(A):
   dic={}
   for x in A:
       if not x in dic:       
          dic[x] = A.count(x)
   return dic
dic = countWords(words)
sorted_items=sorted(dic.items())   
for word in sorted_items:
    print("{0} ---> {1}".format(word[0],word[1]))

"deployment" ---> 2
2017 ---> 1
Actually ---> 1
Also ---> 1
As ---> 1
Bottle ---> 1
But ---> 4
By ---> 1
Dec ---> 1
Django ---> 6
Django! ---> 1
Django20 ---> 2
Flask ---> 1
Hellon ---> 1
It ---> 1
Just ---> 1
MVC ---> 1
Now ---> 1
ORM ---> 1
OS ---> 1
Ppython ---> 1
Pyramid ---> 1
Python ---> 7
Python2 ---> 1
Python3 ---> 1
Python30 ---> 1
The ---> 2
These ---> 1
To ---> 1
US ---> 1
With ---> 1
a ---> 4
about ---> 1
also ---> 1
among ---> 1
and ---> 2
application ---> 6
are ---> 1
as ---> 1
be ---> 2
because ---> 1
bothering ---> 1
build ---> 1
can ---> 3
cause ---> 1
code ---> 1
data ---> 1
databases ---> 1
dependencies ---> 1
develop ---> 2
does ---> 1
easily ---> 1
errors ---> 1
etc ---> 3
famous ---> 1
feedbacks ---> 1
following ---> 2
for ---> 2
framework ---> 2
frameworks ---> 1
friends ---> 1
from ---> 2
frustrates ---> 1
frustrating ---> 1
full ---> 1
generator ---> 1
getting ---> 1
good ---> 1
if ---> 1
in ---> 3
install ---> 1
installation ---> 2
instruction ---> 1
is ---> 1

# Numpy Libraries

In [81]:
import numpy as np
arr = np.arange(0,10)
print(arr)
print(arr+arr)
print(arr-arr)
print(arr*arr) # scalar multiplication
print(arr/arr)
print(arr%arr)
print(1/arr)
print(np.sqrt(arr))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[0 0 0 0 0 0 0 0 0 0]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in remainder
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


In [85]:
import numpy as np
a = [1,2,3]
np.array(a)

array([1, 2, 3])

In [86]:
import numpy as np
a_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(a_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
import numpy as np
np.arange(-100,100,10)

array([-100,  -90,  -80,  -70,  -60,  -50,  -40,  -30,  -20,  -10,    0,
         10,   20,   30,   40,   50,   60,   70,   80,   90])

In [97]:
import numpy as np
print(np.zeros(3))
print(np.zeros((5,5)))

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [98]:
import numpy as np
print(np.ones(3))
print(np.ones((5,5)))

[1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [108]:
import numpy as np
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [2]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
import numpy as np
print(np.random.rand(2)) #uniform distribution
print(np.random.rand(10))
print(np.random.rand(5,5))
print(np.random.randn(3)) #Normal distribution
print(np.random.randint(0,100,3)) #integer distribution

[0.14846082 0.7581122 ]
[0.22586485 0.70254732 0.89610935 0.40376813 0.78839098 0.80837304
 0.70465123 0.57407019 0.35427825 0.71731114]
[[0.29551919 0.76839828 0.58329455 0.19244975 0.14446468]
 [0.25274765 0.86486231 0.71417559 0.87664483 0.43548259]
 [0.1053045  0.34938193 0.9164315  0.90359828 0.69007965]
 [0.79492463 0.01551562 0.18244585 0.36311582 0.4639988 ]
 [0.50873819 0.31826705 0.27638892 0.29120462 0.74677333]]
[-0.12853421 -2.53171714  0.11184015]
[50 15  5]


In [128]:
import numpy as np
arr = np.arange(0,10)
print(arr.shape)
print(arr.reshape(1,10))
print(arr.reshape(10,1))
print(arr.dtype)

(10,)
[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
int32


# Conditional Game

In [ ]:
print("Guess the 5 letter word...!")
word = "apple"
attempt = 1
while(attempt<=5):
    chcount = 0
    while(chcount<=len(word)):
        in_val = input("Enter the " + str(chcount+1) + " Letter : ")
        if(word[chcount]==in_val):
            print("You won you found the "+ str(chcount+1) + "Letter")
            if (chcount + 1 == 5):
                print("You found the word : apple")
            chcount = chcount+1
        else:
            if(attempt == 5):
                print("Sorry You loss the game")
            else:
                print("You loose you have "+ str(5-attempt) + "attempts only")
                attempt = attempt + 1           

Guess the 5 letter word...!
Enter the 1 Letter : a
You won you found the 1Letter
Enter the 2 Letter : b
You loose you have 4attempts only
Enter the 2 Letter : g
You loose you have 3attempts only
Enter the 2 Letter : d
You loose you have 2attempts only
Enter the 2 Letter : p
You won you found the 2Letter
Enter the 3 Letter : p
You won you found the 3Letter
Enter the 4 Letter : l
You won you found the 4Letter
Enter the 5 Letter : e
You won you found the 5Letter
You found the word : apple
