In [2]:
#create array and reshape

import numpy as np
arr = np.arange(0,100)
print(arr.reshape(10,10))


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [13]:
# Create an array of 20 linearly spaced points between 0 and 1
import numpy as np
print(np.linspace(0,1,4))
print(np.linspace(0,1,20))

[0.         0.33333333 0.66666667 1.        ]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [34]:
import numpy as np
print(np.arange(0,36).reshape(6,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [39]:
import numpy as np
print(np.arange(1,26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [42]:
import numpy as np
print(np.arange(1,26).reshape(5,5)[2:,:2])


[[11 12]
 [16 17]
 [21 22]]


In [ ]:
#list is kind of matrix(vector)

In [51]:
import numpy as np
print(np.arange(1,26).reshape(5,5)[1:2,4:])

[[10]]


# pandas

In [64]:
import numpy as np
import pandas as pd
lables = ['a','b','c']
mylist = [1,2,3]
arr = np.array([1,2,3])
d = {'a':1,'b':2,'c':3}
print(pd.Series(mylist,lables))
print(pd.Series(arr))
print(pd.Series(d))

a    1
b    2
c    3
dtype: int64
0    1
1    2
2    3
dtype: int32
a    1
b    2
c    3
dtype: int64


In [67]:
# ordered pair
import pandas as pd
print(pd.Series([1,2],index=['Guru',"Samy"]))

Guru    1
Samy    2
dtype: int64


In [117]:
#Data frame - are nothing but a table
import numpy as np
from numpy.random import randn
import pandas as pd
np.random.seed(109)
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
print("---------Table---------")
print(df) # table
print("---------Select single column---------")
print(df['W']) # Select single column

print("---------Select multiple column---------")
print(df[['W','X']]) # Select multiple column

print("---------Alter the table - operation +---------")
df['new'] = df['W']+ df['X'] # Alter the table - operation
print(df) # Alter the table - result

print("---------Alter the table - operation / ---------")
df['new1'] = df['W'] / df['X'] # Alter the table - operation
print(df) # Alter the table - result

print("---------Alter the table - operation *---------")
df['new2'] = df['W'] * (df['X']*10) # Alter the table - operation
print(df) # Alter the table - result

print("--------drop the column---------")
print(df.drop('new',axis=1)) # Alter the table - result

print("--------drop the column permenently---------")
df.drop('new2',axis=1,inplace=True) 
print(df)

print("--------drop the rows---------")
print(df.drop('E',axis=0))

print("--------Select the row---------")
print(df.loc['A'])

print("--------Select the row based on index---------")
print(df.iloc[1])

print("--------Select the subset of rows and columns---------")
#print(df.loc['D','E'])
print(df.iloc[1:3])

print("--------Select the values based on conditions---------")
print(df>0)
print(df[df['W']>0])

print("--------Select the values based on conditions specific column---------")
print(df[df['W']>0]['Y'])

print("--------Select the values based on conditions specific column---------")
print(df[(df['W']>0) & (df['Y']>1)])

print("--------Add column with value(index)---------")
newinde = 'CA DS AR FR GT'.split()
df['Serial'] = newinde
print(df)

print("--------Change |Index---------")
print(df.set_index('Serial'))


---------Table---------
          W         X         Y         Z
A -0.187735  2.440637 -0.940908  0.613912
B  0.735627  0.972918  0.259195 -0.074075
C -0.177688 -0.838744 -0.156287 -0.341762
D  0.818730 -0.092614  0.508081 -1.754222
E -0.364818 -0.030919 -0.126144  0.299181
---------Select single column---------
A   -0.187735
B    0.735627
C   -0.177688
D    0.818730
E   -0.364818
Name: W, dtype: float64
---------Select multiple column---------
          W         X
A -0.187735  2.440637
B  0.735627  0.972918
C -0.177688 -0.838744
D  0.818730 -0.092614
E -0.364818 -0.030919
---------Alter the table - operation +---------
          W         X         Y         Z       new
A -0.187735  2.440637 -0.940908  0.613912  2.252902
B  0.735627  0.972918  0.259195 -0.074075  1.708545
C -0.177688 -0.838744 -0.156287 -0.341762 -1.016432
D  0.818730 -0.092614  0.508081 -1.754222  0.726116
E -0.364818 -0.030919 -0.126144  0.299181 -0.395737
---------Alter the table - operation / ---------
         

In [126]:
# Multilevel indexing
import numpy as np
import pandas as pd
a = ['a','a','a','b','b','b']
b= [1,2,3,1,2,3]
c= list(zip(a,b))
d=pd.MultiIndex.from_tuples(c)
print(d)
df = pd.DataFrame(np.random.randn(6,2),index=d,columns=['A','B'])
print(df)
print(df.loc['a'].loc[1])

MultiIndex(levels=[['a', 'b'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])
            A         B
a 1  0.036181 -1.193278
  2 -0.158102  0.013418
  3 -0.472347 -0.208106
b 1  1.441544 -1.671095
  2  0.544559  1.261322
  3  0.962837 -0.279902
A    0.036181
B   -1.193278
Name: 1, dtype: float64


In [139]:
# Groupby

import pandas as pd
data={'a':['a1','a2','a3','a4','a4'],
    'b':['b1','b2','b3','b4','b4'],
    'c':[10,20,30,40,50]}
df = pd.DataFrame(data)
print(df)
by_b = df.groupby('b')
print(by_b.mean())
print(df.groupby('b').mean())
print(df.groupby('b').describe())
print(df.groupby('b').describe().transpose())

    a   b   c
0  a1  b1  10
1  a2  b2  20
2  a3  b3  30
3  a4  b4  40
4  a4  b4  50
     c
b     
b1  10
b2  20
b3  30
b4  45
     c
b     
b1  10
b2  20
b3  30
b4  45
       c                                              
   count  mean       std   min   25%   50%   75%   max
b                                                     
b1   1.0  10.0       NaN  10.0  10.0  10.0  10.0  10.0
b2   1.0  20.0       NaN  20.0  20.0  20.0  20.0  20.0
b3   1.0  30.0       NaN  30.0  30.0  30.0  30.0  30.0
b4   2.0  45.0  7.071068  40.0  42.5  45.0  47.5  50.0
b          b1    b2    b3         b4
c count   1.0   1.0   1.0   2.000000
  mean   10.0  20.0  30.0  45.000000
  std     NaN   NaN   NaN   7.071068
  min    10.0  20.0  30.0  40.000000
  25%    10.0  20.0  30.0  42.500000
  50%    10.0  20.0  30.0  45.000000
  75%    10.0  20.0  30.0  47.500000
  max    10.0  20.0  30.0  50.000000


In [143]:
# merging

import pandas as pd
df1=pd.DataFrame({'a11':['a1','a2','a3','a4','a4'],
    'b11':['b1','b2','b3','b4','b4'],
    'c11':[10,20,30,40,50]},index=[4,5,6,7])
df2=pd.DataFrame({'a22':['a1','a2','a3','a4','a4'],
    'b22':['b1','b2','b3','b4','b4'],
    'c22':[10,20,30,40,50]},index=[8,9,10,11])
df3=pd.DataFrame({'a33':['a1','a2','a3','a4','a4'],
    'b33':['b1','b2','b3','b4','b4'],
    'c33':[10,20,30,40,50]},index=[12,13,14,15])
df3.concat[df1,df2]


In [ ]:
# joining
left.join(right)

# unique
df['col2'].unique()

# unique count
df['col2'].nunique()

# value count
df['col2'].value_counts()

# applying fucntions
def times2(x):
    return x*2

df['col1'].apply(times2)

df['col1'].apply(len)

df.isnull()
df.dropna()

df.head()
df.fillna('fill')

In [153]:
import pandas as pd
df=pd.read_excel('Excel_Sample.xlsx')
print(df)
df=pd.read_csv('example')
print(df)
df=pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')
print(df)
df.to_csv('example',index=False)
print(df)
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet2')
print(df)

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: []
Index: []


In [156]:
import pandas as pd
df=pd.read_csv('date-1.csv')
df.to_csv('example')
print(df)

   OD01  1  1.1  450  2016-01-24  1.2  Apple iPhone 4S
0  OD01  1    1  450  2016-01-24    2  Apple iPhone 5S
1  OD01  1    1  450  2016-01-24    3   Apple iPhone 6
2  OD02  2    2  400  2016-01-24    1  Apple iPhone 4S
3  OD02  2    2  400  2016-01-24    2  Apple iPhone 5S
4  OD02  2    2  400  2016-01-24    3   Apple iPhone 6
5  OD03  2    1  350  2016-01-25    1  Apple iPhone 4S
6  OD03  2    1  350  2016-01-25    2  Apple iPhone 5S
7  OD03  2    1  350  2016-01-25    3   Apple iPhone 6


In [157]:
print('cd'.partition('cd'))

('', 'cd', '')
