In [1]:
import numpy as np

In [3]:
arr = np.arange(0,20,2)

In [4]:
arr + arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [5]:
arr * arr

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

In [6]:
print(arr * arr)

[  0   4  16  36  64 100 144 196 256 324]


In [7]:
print(arr + arr)

[ 0  4  8 12 16 20 24 28 32 36]


In [8]:
print(arr - arr)

[0 0 0 0 0 0 0 0 0 0]


In [9]:
print(arr // arr) # 0/0 is undefined.

[0 1 1 1 1 1 1 1 1 1]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [10]:
print(1/arr) # divide by zero condition

[       inf 0.5        0.25       0.16666667 0.125      0.1
 0.08333333 0.07142857 0.0625     0.05555556]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [11]:
print(arr ** 3)

[   0    8   64  216  512 1000 1728 2744 4096 5832]


### Universal functions

In [12]:
np.sqrt(arr) #square root

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

In [13]:
np.exp(arr) #exponential

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07])

In [14]:
np.max(arr)

18

In [15]:
np.min(arr)

0

In [16]:
np.sum(arr)

90

In [17]:
np.mean(arr)

9.0

In [18]:
np.count_nonzero(arr)

9

In [19]:
np.average(arr)

9.0

In [20]:
np.sin(arr)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

In [21]:
np.cos(arr)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671])

In [22]:
np.tan(arr)

array([ 0.        , -2.18503986,  1.15782128, -0.29100619, -6.79971146,
        0.64836083, -0.63585993,  7.24460662,  0.30063224, -1.13731371])

In [23]:
np.cosh(arr)

array([1.00000000e+00, 3.76219569e+00, 2.73082328e+01, 2.01715636e+02,
       1.49047916e+03, 1.10132329e+04, 8.13773957e+04, 6.01302142e+05,
       4.44305526e+06, 3.28299846e+07])

In [24]:
np.sinh(arr)

array([0.00000000e+00, 3.62686041e+00, 2.72899172e+01, 2.01713157e+02,
       1.49047883e+03, 1.10132329e+04, 8.13773957e+04, 6.01302142e+05,
       4.44305526e+06, 3.28299846e+07])

In [25]:
np.tanh(arr)

array([0.        , 0.96402758, 0.9993293 , 0.99998771, 0.99999977,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [26]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176])

In [27]:
np.array(["a","b","c",4,5,6])

array(['a', 'b', 'c', '4', '5', '6'], dtype='<U1')

In [28]:
np.array(["ram","shyam",4,5])

array(['ram', 'shyam', '4', '5'], dtype='<U5')

In [29]:
l = [1,2,3]

In [30]:
l

[1, 2, 3]

In [31]:
np.array(l)

array([1, 2, 3])

In [32]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [33]:
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [34]:
print(my_matrix[2][1])

8


In [35]:
np.array(my_matrix) # array of lists is matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [38]:
np.arange(0,11,5)

array([ 0,  5, 10])

In [39]:
np.arange(0,11,3)

array([0, 3, 6, 9])

### Zeros and Ones

In [40]:
np.zeros(3)

array([0., 0., 0.])

In [41]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [44]:
np.ones(2)

array([1., 1.])

In [45]:
np.ones(3)

array([1., 1., 1.])

In [46]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.ones((3,3))*2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [48]:
np.linspace(0,10,2)

array([ 0., 10.])

In [49]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [50]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [51]:
np.linspace(0,50,20)

array([ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579,
       13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053,
       26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526,
       39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ])

In [52]:
np.eye((3)) # Identity matrices are always square matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.random.rand(2)

array([0.98563432, 0.76745471])

In [54]:
np.random.rand(10)

array([0.6873198 , 0.28578033, 0.32144257, 0.41444158, 0.84351165,
       0.36300901, 0.1645648 , 0.98796623, 0.17752699, 0.54248348])

In [55]:
np.random.rand(5,5)

array([[0.30752464, 0.78060634, 0.02554424, 0.43315846, 0.93390955],
       [0.73071666, 0.78465783, 0.81933408, 0.34751949, 0.19613129],
       [0.98012385, 0.32304328, 0.4829846 , 0.12090926, 0.11563581],
       [0.3602435 , 0.95510921, 0.70145732, 0.98142889, 0.64745499],
       [0.06356848, 0.65046101, 0.44783174, 0.63025512, 0.71349025]])

In [57]:
np.random.randn(2) # non uniform random distributions

array([-0.43521001,  0.46146771])

In [58]:
np.random.randn(10)

array([ 0.61524542, -1.29040075,  1.12884232,  3.69863116, -1.83020039,
       -0.16513917, -1.78911136, -1.14157101,  0.03621016, -0.8620961 ])

In [2]:
np.random.randn(5,5)

array([[ 0.93925185,  0.20966331, -0.91031144,  0.79399211, -1.92299558],
       [ 0.35301759,  1.3391205 ,  2.12847913,  0.82515592,  0.33935412],
       [-0.32488436, -1.4047252 , -0.61570548, -0.32072223,  0.03847029],
       [ 0.34977595, -1.20174916,  1.00513427, -0.24341521, -0.12889371],
       [-1.80745011,  0.25683228, -1.51239641, -0.23374553,  0.16460031]])

In [3]:
np.random.randint(1,100) # integers between 0 to 100

39

In [5]:
np.random.randint(1,100,10) # 10 numbers between 1 and 100

array([65, 45, 11, 17, 39, 63, 57, 74, 90, 88])

### Array Attributes and Methods

In [13]:
arr = np.arange(25)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
ranarr = np.random.randint(0,50,10)

In [16]:
ranarr

array([22, 41, 28, 31,  8, 17, 30, 30, 17,  5])

### Reshape

In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
ranarr.min()

5

In [19]:
ranarr.argmin()

9

In [20]:
ranarr.argmax()

1

In [21]:
arr.min()

0

In [22]:
arr.argmin()

0

In [24]:
ranarr

array([22, 41, 28, 31,  8, 17, 30, 30, 17,  5])

In [25]:
# argmin and argmax returns the index of minimum and maximum value

In [27]:
arr.shape

(25,)

In [28]:
ranarr.shape

(10,)

In [29]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [31]:
arr.dtype

dtype('int32')