In [2]:
#print("Enter a word")
word="apple"
print("Guess the word:")
print("-----")
a=input()
while (a.isalpha()):
    if(a==word[0]):
        print("good guess")
        break
    elif(a!=word[0]):
        print("try again")
        a=input()

Guess the word:
-----
f
try again
a
good guess


In [9]:
import numpy as np
a=np.ones(10)*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [13]:
a=np.arange(10,51,3)
print(a)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [12]:
a=np.ones(10)*10
print(a)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [21]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [39]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [54]:
a1=np.arange(1,26).reshape(5,5)
print(a1)
print("--------------")
print(a1[1:,:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
--------------
[[ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [61]:
a1=np.arange(1,26).reshape(5,5)
print(a1)
print(a1[:3,1:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 2]
 [ 7]
 [12]]


In [68]:
a1=np.arange(1,26).reshape(5,5)
print(a1)
a1.std()
a1.sum(axis=1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([ 15,  40,  65,  90, 115])

In [70]:
import numpy as np
import pandas as pd

In [71]:
mylist=[1,2,3]
labels=['a','b','c']
pd.Series(mylist)

0    1
1    2
2    3
dtype: int64

In [72]:
mylist=[1,2,3]
labels=['a','b','c']
pd.Series(mylist,labels)

a    1
b    2
c    3
dtype: int64

In [81]:
mylist=[1,2,3]
labels=['a','b','c']
arr=np.array([10,20,30])
pd.Series(mylist,labels)
pd.Series(arr,labels)
d={'a':1,'b':2,'c':3}
pd.Series(d)

a    1
b    2
c    3
dtype: int64