The begining

In [4]:
print('Hello world')
print('vivek')

Hello world
vivek


Arithmetic operator

In [5]:
2+4

6

## 

In [6]:
2-4

-2

In [7]:
4-2

2

In [8]:
4*5

20

In [9]:
5/2

2.5

In [10]:
5%2

1

In [13]:
5//2

2

In [16]:
5**2

25

In [21]:
5+1-4-(5**7)/6

-13018.833333333334

In [18]:
2**10

1024

In [22]:
6-(30/5)

0.0

Assignement operator with Arithemetic operator

In [23]:
a=2


In [24]:
a+10

12

In [25]:
b=5.0
a+b

7.0

String Assignment

In [27]:
c='hello'

In [36]:
c

'hello'

In [34]:
h="hello"
h

'hello'

In [35]:
"Hello Let's try this one"

"Hello Let's try this one"

# Income tax Calculation

In [43]:
income=10000
taxpercent=10
taxableamount=income*(taxpercent/100)
taxableamount


1000.0

# Area of circle

In [54]:
r=5
pie=3.14
Area=pie*(r**2)
Area

78.5

In [49]:
b=round(20.345,2)
b

20.34

# How to convert anything to integer

In [52]:
Area=int(Area)
Area

78

In [53]:
Area=float(Area)
Area

78.0

# Multi line  \ is used to avoid appostrpphy s or single or quote

In [56]:
'''hello
k.jhkjhgklg'''

'hello\nk.jhkjhgklg'

In [60]:
M='I dont\'t like to eat cheese'
print(M)

I dont't like to eat cheese


# String concate

In [64]:
a="Vivek "
b="Gupta"
c=a+b
print(c)

Vivek Gupta


# HOW TO PRINT FORMATTTED THINGS

In [66]:
Name="vivek"
age=29
print("Myname:{one} and my age is {two}".format(one=Name,two=age))

Myname:vivek and my age is 29


In [77]:
print(3*"hello ")
print(300*"hello "+"\n\nThe End")

hello hello hello 
hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hel

In [78]:
"vivek".upper()

'VIVEK'

In [79]:
len("hello world")

11

In [84]:
"Hi  my name is Vivek".replace("Vivek","Gupta")

'Hi  my name is Gupta'

In [96]:
bob="my name is Vivek \n"*6
bob.replace("Vivek","vivu")
print(bob)

my name is Vivek 
my name is Vivek 
my name is Vivek 
my name is Vivek 
my name is Vivek 
my name is Vivek 



In [97]:
bob="my name is Vivek \n"*5
c=bob.replace("Vivek","vivu")
print(c)
print(bob)

my name is vivu 
my name is vivu 
my name is vivu 
my name is vivu 
my name is vivu 

my name is Vivek 
my name is Vivek 
my name is Vivek 
my name is Vivek 
my name is Vivek 



In [100]:
bob="vivek is a nice chap"
bob.split()

['vivek', 'is', 'a', 'nice', 'chap']

In [103]:
a=5
b=1
a>b

True

In [104]:
a=5
b=1

a==b

False

In [107]:
a!=b

True

In [ ]:
(a==b) or (b<a)

In [3]:
r=input('enter radious value = ')
pie=3.14
Area=pie*(int(r)**2)
print(Area)

enter radious value = 5
78.5


In [13]:
employeesalary=input('enter the salary=')
taxslab=input('enter the taxslab=')
taxamount=int(employeesalary)*(int(taxslab)/100)
netsalary=int(employeesalary)-int(taxamount)
print(netsalary)
print(taxamount)









enter the salary=100000
enter the taxslab=10
90000
10000.0


In [16]:
var1=10
print ('here is a number: %s'%(var1))

here is a number: 10


In [22]:
n=1
m=2
print('the sume of %s and %s is equal to %s'%(n,m,n+m))

the sume of 1 and 2 is equal to 3


In [26]:
var='helo world'
var[4]


'y'

In [30]:
var='helo world'
var[-1]


'd'

In [36]:
var='helo world'
var[:2]


'he'

In [37]:
var='helo world'
var[2:]

'lo world'

In [38]:
var='helo world'
var[-1]

'd'

In [45]:
var='hello'
print(var[0:5])
print(var[5:0])

hello



In [50]:
var='hello'
var.islower()


True

In [51]:
var='HELLO'
var.isupper()

True

In [52]:
var='HELLO'
var.isalpha()

True

# list

In [53]:
z=[1,2,3,4]

In [54]:
x=[1,2,3,'a']

In [68]:
y=[2,x]
print(y)
y[1][3]

[2, [1, 2, 3, 'a']]


'a'

# dictionary

In [70]:
d={'Name': 'Zara', 'Age': 7, 'Class': 'First'}
print(d)

{'Name': 'Zara', 'Age': 7, 'Class': 'First'}


In [80]:
z={1:'abc',2:'hgf'}
print(z[1])
print(z[2])
b={1:[1,2,3]}
print(b[1][1])

abc
hgf
2


In [84]:
##reverse
newlist=['a','b','c','d','e']
newlist.reverse()
newlist

['e', 'd', 'c', 'b', 'a']

In [85]:
##sort
a=[4,7,1,9,2,3]
a.sort()
a

[1, 2, 3, 4, 7, 9]

In [89]:
##append
e=[1,2,3]
e.append(4)
e


[1, 2, 3, 4]

In [90]:
b=[1,2,3]
c=b+[5]
c

[1, 2, 3, 5]

In [94]:
t=(1,2,3,45)
print(t)


(1, 2, 3, 45)


In [95]:
max(t)

45

In [96]:
45 in t

True

In [97]:
len(t)

4

In [99]:
t2=(1,2,3,5)
t2[1:3]

(2, 3)

# SET is unorderd distinct elements

In [100]:
s={1,2,3}

In [101]:
len(s)

3

In [102]:
max(s)

3

In [103]:
min(s)

1

In [105]:
2 in s

True

In [106]:
5 in s

False

In [107]:
s2={4,5}
s.update(s2)
s

{1, 2, 3, 4, 5}

In [110]:
s3={1,1,1,1,3,3,34,4,4,4,4}
s3


{1, 3, 4, 34}

In [117]:
d=set()
d.add(10)
d

{10}

In [126]:

a=0
b=3

if(a>b):
 print('a is greater then b')
elif(a==b):
 print('a and b is equal')
elif(b>a):
 print('a smaller too b')

a smaller too b


In [136]:
employeesalary=int(input('enter the salary='))
##taxslab=input('enter the taxslab=')
if(employeesalary >= 10000 and employeesalary <=20000):
 taxamount=int(employeesalary)*(int(3)/100)
 netsalary=int(employeesalary)-int(taxamount)
 print('1')
 print(netsalary)
 print(taxamount)
elif(employeesalary >= 20001 and employeesalary <=30000):
 print('2')
 taxamount=int(employeesalary)*(int(5)/100)
 netsalary=int(employeesalary)-int(taxamount)
 print(netsalary)
 print(taxamount)
elif(employeesalary >= 30001 and employeesalary <=40000):
 print('3')
 taxamount=int(employeesalary)*(int(8)/100)
 netsalary=int(employeesalary)-int(taxamount)
 print(netsalary)
 print(taxamount)

enter the salary=25000
2
23750
1250.0


# CLass declaration

In [9]:
class vivek:
   print('how are you')
   info="Vivek is a DB Guy"
    

how are you


# Class variable 

In [10]:
a=vivek()
a.name="Gupta"
b=vivek()
b.name=("vivu")
print(a.name)
print(b.name)
print(b.info)
print(b.info)

Gupta
vivu
Vivek is a DB Guy
Vivek is a DB Guy


In [20]:
class dog:
    def __init__(self,name,age,teeth):
        self.name=name
        self.age=age
        self.teeth=teeth
dog1=dog("erfqr","34","33")
print(dog1.name)
print(dog1.age)

erfqr
34


In [12]:
import numpy as np
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [30]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
arr/arr


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [32]:
1/arr


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [34]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [35]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [37]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [45]:
print(np.max(arr))
print(np.min(arr))


9
0


AttributeError: module 'numpy' has no attribute 'count'

In [46]:
print(np.average(arr))


4.5


In [48]:
print(np.count(arr))


AttributeError: module 'numpy' has no attribute 'count'

In [49]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [50]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [51]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [18]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [19]:
np.array(my_list)

array([1, 2, 3])

In [20]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [21]:
a=np.array(my_matrix)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,11,5)

array([ 0,  5, 10])

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.random.rand(5,5)

array([[0.22745989, 0.84964915, 0.22120339, 0.3536394 , 0.43248493],
       [0.38579799, 0.33738252, 0.36240452, 0.07482048, 0.27331816],
       [0.23344821, 0.90655112, 0.11393168, 0.16495942, 0.55276264],
       [0.35168883, 0.62613992, 0.23363576, 0.68200687, 0.268802  ],
       [0.6951642 , 0.46292317, 0.89230943, 0.32806603, 0.23069074]])

In [33]:
np.random.randn(5,5)

array([[ 0.85581072, -1.24417627,  2.28634377, -0.74412696, -1.98067975],
       [ 1.96821964,  1.92383806, -1.29715299,  1.38521115, -1.78161594],
       [-0.87605939,  2.15794992,  0.62371208, -0.2980062 , -0.33251824],
       [ 0.57785536,  2.24590554, -0.75725807,  0.1461155 , -0.65207055],
       [-0.71428938, -2.57448836, -0.57735192, -1.59153658,  0.9638163 ]])

In [34]:
np.random.randint(1,100)

82

In [35]:
np.random.randint(1,100,10)

array([14, 56, 37, 21, 83, 49, 98, 91, 25, 81])

In [49]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr=np.random.randint(0,50,10)
ranarr

array([48, 18, 47,  3,  2, 21, 44, 35, 22, 37])

In [58]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [107]:
ranarr

array([22, 10,  9, 37, 44, 35, 15, 19,  7, 47])

In [109]:
np.argmax(ranarr)

9

In [110]:
np.argmin(ranarr)

8

In [56]:
arr.shape

(25,)

In [2]:
arr.reshape(25,1)

NameError: name 'arr' is not defined

In [113]:
arr.dtype

dtype('int32')

In [10]:
import numpy as np
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
axx=np.arange(0,100)
axx


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [47]:
axx.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [48]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [43]:
np.linspace(12,25,12)

array([12.        , 13.18181818, 14.36363636, 15.54545455, 16.72727273,
       17.90909091, 19.09090909, 20.27272727, 21.45454545, 22.63636364,
       23.81818182, 25.        ])

In [52]:
import numpy as np
arry=np.arange(12,16)
arr2=np.arrange()

array([12, 13, 14, 15])

NameError: name 'arry' is not defined

In [63]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
mat[:2,:2]

array([[1, 2],
       [6, 7]])

In [65]:
mat[2:5,2:5]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [83]:
mat[0:2,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [85]:
mat[3:,2:]

array([[18, 19, 20],
       [23, 24, 25]])

In [90]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [92]:
mat[3:4,4:]

array([[20]])

In [108]:
mat[:3,1:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [110]:
mat[4:5]

array([[21, 22, 23, 24, 25]])

In [113]:
mat[3:5]


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [119]:
print(np.sum(mat))
print(np.min(mat))
print(np.max(mat))

325
1
25


In [118]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [123]:
abb=mat[4:5]+mat[3:4]+mat[2:3]+mat[1:2]+mat[:1]
abb
np.sum(abb)

325

In [124]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [125]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

# PANDAS


In [133]:
d={'a':10,'b':20,'c':30}
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])


In [8]:
import numpy as np
import pandas as pd

In [136]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [137]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [138]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [145]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [146]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [151]:
ser1=pd.Series([1,2,3,4],index=['USA','Germany','USSR','Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [156]:
ser2=pd.Series([1,2,5,4],index=['USA','Germany','Italy','Japan'])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [157]:
ser1['USA']

1

In [158]:
ser2['USA']

1

In [159]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [9]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)


NameError: name 'np' is not defined

In [227]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [173]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [229]:
df[['W','Z','X']]

W         Z         X
A  0.302665 -1.159119  1.693723
B -0.134841  0.184502  0.390528
C  0.807706  0.329646  0.072960
D -0.497104  0.484752 -0.754070
E -0.116773  1.996652  1.901755

In [199]:
type(df['W'])

pandas.core.series.Series

In [230]:
df['New']=df['W']+df['Y']
df

W         X         Y         Z       New
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [231]:
df['old']=df['New']*10
df

W         X         Y         Z       New        old
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420 -14.034205
B -0.134841  0.390528  0.166905  0.184502  0.032064   0.320639
C  0.807706  0.072960  0.638787  0.329646  1.446493  14.464929
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510 -14.405104
E -0.116773  1.901755  0.238127  1.996652  0.121354   1.213536

In [224]:
df.drop('New',axis=1)

W         X         Y         Z        old
A  2.706850  0.628133  0.907969  0.503826  36.148193
B  0.651118 -0.319318 -0.848077  0.605965  -1.969590
C -2.018168  0.740122  0.528813 -0.589001 -14.893547
D  0.188695 -0.758872 -0.933237  0.955057  -7.445419
E  0.190794  1.978757  2.605967  0.683509  27.967616

In [225]:
df.drop('New',axis=1,inplace=True)


In [226]:
df.drop('D',axis=0,inplace=True)

In [232]:
df.loc['B','Y']

0.16690463609281317

In [233]:
df.loc[['A','B'],['W','Y']]

W         Y
A  0.302665 -1.706086
B -0.134841  0.166905

In [236]:
df.loc[['A','B','C']]

W         X         Y         Z       New        old
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420 -14.034205
B -0.134841  0.390528  0.166905  0.184502  0.032064   0.320639
C  0.807706  0.072960  0.638787  0.329646  1.446493  14.464929

In [241]:
df.iloc[:3]

W         X         Y         Z       New        old
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420 -14.034205
B -0.134841  0.390528  0.166905  0.184502  0.032064   0.320639
C  0.807706  0.072960  0.638787  0.329646  1.446493  14.464929

In [258]:
df

W         X         Y         Z       New        old
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420 -14.034205
B -0.134841  0.390528  0.166905  0.184502  0.032064   0.320639
C  0.807706  0.072960  0.638787  0.329646  1.446493  14.464929
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510 -14.405104
E -0.116773  1.901755  0.238127  1.996652  0.121354   1.213536

In [245]:
df>0

W      X      Y      Z    New    old
A   True   True  False  False  False  False
B  False   True   True   True   True   True
C   True   True   True   True   True   True
D  False  False  False   True  False  False
E  False   True   True   True   True   True

In [247]:
df[df>0]

W         X         Y         Z       New        old
A  0.302665  1.693723       NaN       NaN       NaN        NaN
B       NaN  0.390528  0.166905  0.184502  0.032064   0.320639
C  0.807706  0.072960  0.638787  0.329646  1.446493  14.464929
D       NaN       NaN       NaN  0.484752       NaN        NaN
E       NaN  1.901755  0.238127  1.996652  0.121354   1.213536

In [248]:
df[df['W']>0]

W         X         Y         Z       New        old
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420 -14.034205
C  0.807706  0.072960  0.638787  0.329646  1.446493  14.464929

In [253]:
df[df['W']>0]['Y']

A   -1.706086
C    0.638787
Name: Y, dtype: float64

In [254]:
df[df['W']>0][['Y','X']]

Y         X
A -1.706086  1.693723
C  0.638787  0.072960

In [262]:
df[(df['W']>0) & (df['New']>0)] 

W        X         Y         Z       New        old
C  0.807706  0.07296  0.638787  0.329646  1.446493  14.464929

In [266]:
df[(df['X']>0) | (df['New']>0)] 

W         X         Y         Z       New        old
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420 -14.034205
B -0.134841  0.390528  0.166905  0.184502  0.032064   0.320639
C  0.807706  0.072960  0.638787  0.329646  1.446493  14.464929
E -0.116773  1.901755  0.238127  1.996652  0.121354   1.213536

In [267]:
df

W         X         Y         Z       New        old
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420 -14.034205
B -0.134841  0.390528  0.166905  0.184502  0.032064   0.320639
C  0.807706  0.072960  0.638787  0.329646  1.446493  14.464929
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510 -14.405104
E -0.116773  1.901755  0.238127  1.996652  0.121354   1.213536

In [268]:
df.reset_index()

index         W         X         Y         Z       New        old
0     A  0.302665  1.693723 -1.706086 -1.159119 -1.403420 -14.034205
1     B -0.134841  0.390528  0.166905  0.184502  0.032064   0.320639
2     C  0.807706  0.072960  0.638787  0.329646  1.446493  14.464929
3     D -0.497104 -0.754070 -0.943406  0.484752 -1.440510 -14.405104
4     E -0.116773  1.901755  0.238127  1.996652  0.121354   1.213536

In [274]:
newvar='CA NY DC WY CO'.split()


In [275]:
df['States']=newvar

In [276]:
df

W         X         Y         Z       New        old States
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420 -14.034205     CA
B -0.134841  0.390528  0.166905  0.184502  0.032064   0.320639     NY
C  0.807706  0.072960  0.638787  0.329646  1.446493  14.464929     DC
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510 -14.405104     WY
E -0.116773  1.901755  0.238127  1.996652  0.121354   1.213536     CO

In [277]:
df.set_index('States')

W         X         Y         Z       New        old
States                                                             
CA      0.302665  1.693723 -1.706086 -1.159119 -1.403420 -14.034205
NY     -0.134841  0.390528  0.166905  0.184502  0.032064   0.320639
DC      0.807706  0.072960  0.638787  0.329646  1.446493  14.464929
WY     -0.497104 -0.754070 -0.943406  0.484752 -1.440510 -14.405104
CO     -0.116773  1.901755  0.238127  1.996652  0.121354   1.213536

In [278]:
df.set_index('States',inplace=True)

In [297]:
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [298]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [299]:
df=pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1  0.187125 -0.732845
   2 -1.382920  1.482495
   3  0.961458 -2.141212
G2 1  0.992573  1.192241
   2 -1.046780  1.292765
   3 -1.467514 -0.494095

In [300]:
df.loc['G1'].loc[1]

A    0.187125
B   -0.732845
Name: 1, dtype: float64

In [306]:
import pandas as pd
data={'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
      'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
     'Sales':[200,100,300,400,500,600]}

In [309]:
df=pd.DataFrame(data)
df.groupby('Company')

In [310]:
by_comp=df.groupby('Company')

In [311]:
by_comp.mean()

Sales
Company       
FB         550
GOOG       150
MSFT       350

In [312]:
by_comp.sum()

Sales
Company       
FB        1100
GOOG       300
MSFT       700

In [313]:
df.groupby('Company').mean()

Sales
Company       
FB         550
GOOG       150
MSFT       350

In [317]:
df.groupby('Company').min()

Person  Sales
Company                
FB          Carl    500
GOOG     Charlie    100
MSFT         Amy    300

In [318]:
df.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [319]:
by_comp.describe()

Sales                                                     
        count   mean        std    min    25%    50%    75%    max
Company                                                           
FB        2.0  550.0  70.710678  500.0  525.0  550.0  575.0  600.0
GOOG      2.0  150.0  70.710678  100.0  125.0  150.0  175.0  200.0
MSFT      2.0  350.0  70.710678  300.0  325.0  350.0  375.0  400.0

In [320]:
by_comp.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   550.000000  150.000000  350.000000
      std     70.710678   70.710678   70.710678
      min    500.000000  100.000000  300.000000
      25%    525.000000  125.000000  325.000000
      50%    550.000000  150.000000  350.000000
      75%    575.000000  175.000000  375.000000
      max    600.000000  200.000000  400.000000

In [321]:
by_comp.describe().transpose()['GOOG']

Sales  count      2.000000
       mean     150.000000
       std       70.710678
       min      100.000000
       25%      125.000000
       50%      150.000000
       75%      175.000000
       max      200.000000
Name: GOOG, dtype: float64

In [322]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                 'B':['B0','B1','B2','B3'],
                 'C':['C0','C1','C2','C3'],
                 'D':['D0','D1','D2','D3']},
                index=[0,1,2,3])

In [325]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [323]:
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                 'B':['B4','B5','B6','B7'],
                 'C':['C4','C5','C6','C7'],
                 'D':['D4','D5','D6','D7']},
                index=[4,5,6,7])

In [328]:
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
                 'B':['B8','B9','B10','B11'],
                 'C':['C8','C9','C10','C11'],
                 'D':['D8','D9','D10','D11']},
                index=[8,9,10,11])

In [329]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [11]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)

In [47]:
df5=pd.DataFrame({'key1':['K0','K1','K2','K3'],
                 'B':['B8','B9','B10','B11'],
                 'C':['C8','C9','C10','C11'],
                 'D':['D8','D9','D10','D11']},
                index=[8,9,10,11])

In [48]:
df6=pd.DataFrame({'key2':['K0','K1','K2','K3'],
                 'E':['B1','B2','B3','B4'],
                 'F':['C1','C2','C3','C4'],
                 'G':['D1','D2','D3','D4']},
                index=[1,2,3,4])

In [49]:
pd.merge(df5,df6,on=['key1','key2'])

KeyError: 'key1'

In [50]:
df5.join(df6)

key1    B    C    D key2    E    F    G
8    K0   B8   C8   D8  NaN  NaN  NaN  NaN
9    K1   B9   C9   D9  NaN  NaN  NaN  NaN
10   K2  B10  C10  D10  NaN  NaN  NaN  NaN
11   K3  B11  C11  D11  NaN  NaN  NaN  NaN

In [52]:
df5.join(df6,how='outer')

key1    B    C    D key2    E    F    G
1   NaN  NaN  NaN  NaN   K0   B1   C1   D1
2   NaN  NaN  NaN  NaN   K1   B2   C2   D2
3   NaN  NaN  NaN  NaN   K2   B3   C3   D3
4   NaN  NaN  NaN  NaN   K3   B4   C4   D4
8    K0   B8   C8   D8  NaN  NaN  NaN  NaN
9    K1   B9   C9   D9  NaN  NaN  NaN  NaN
10   K2  B10  C10  D10  NaN  NaN  NaN  NaN
11   K3  B11  C11  D11  NaN  NaN  NaN  NaN

In [56]:
import numpy as np
import pandas as pd
df=pd.read_excel('Excel_Sample.xlsx')
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [61]:
import numpy as np
import pandas as pd
df3=pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')
df3

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [59]:
df1=pd.read_csv('example')
df1

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [62]:
df.to_csv('Myfile',index=False)

In [63]:
df.to_excel('Excel_Myfile.xlsx',index=False)

In [65]:
df_user=pd.read_csv('u.user')
df_user

1|24|M|technician|85711
0              2|53|F|other|94043
1             3|23|M|writer|32067
2         4|24|M|technician|43537
3              5|33|F|other|15213
4          6|42|M|executive|98101
5      7|57|M|administrator|91344
6      8|36|M|administrator|05201
7            9|29|M|student|01002
8            10|53|M|lawyer|90703
9             11|39|F|other|30329
10            12|28|F|other|06405
11         13|47|M|educator|29206
12        14|45|M|scientist|55106
13         15|49|F|educator|97301
14    16|21|M|entertainment|10309
15       17|30|M|programmer|06355
16            18|35|F|other|37212
17        19|40|M|librarian|02138
18        20|42|F|homemaker|95660
19           21|26|M|writer|30068
20           22|25|M|writer|40206
21           23|30|F|artist|48197
22           24|21|F|artist|94533
23         25|39|M|engineer|55107
24         26|49|M|engineer|21044
25        27|40|F|librarian|30030
26           28|32|M|writer|55369
27       29|41|M|programmer|94043
28           30|7|M|student|55436
29           31|24|M|artist|10003
..                            ...
912          914|44|F|other|08105
913  915|50|M|entertainment|60614
914       916|27|M|engineer|N2L5N
915        917|22|F|student|20006
916      918|40|M|scientist|70116
917          919|25|M|other|14216
918         920|30|F|artist|90008
919        921|20|F|student|98801
920  922|29|F|administrator|21114
921        923|21|M|student|E2E3R
922          924|29|M|other|11753
923       925|18|F|salesman|49036
924  926|49|M|entertainment|01701
925     927|23|M|programmer|55428
926        928|21|M|student|55408
927      929|44|M|scientist|53711
928      930|28|F|scientist|07310
929       931|60|M|educator|33556
930       932|58|M|educator|06437
931        933|28|M|student|48105
932       934|61|M|engineer|22902
933         935|42|M|doctor|66221
934          936|24|M|other|32789
935       937|48|M|educator|98072
936     938|38|F|technician|55038
937        939|26|F|student|33319
938  940|32|M|administrator|02215
939        941|20|M|student|97229
940      942|48|F|librarian|78209
941        943|22|M|student|77841

[942 rows x 1 columns]

In [67]:
df_user1=pd.read_csv('u.user',delimiter='|')
df_user1

1  24  M     technician  85711
0      2  53  F          other  94043
1      3  23  M         writer  32067
2      4  24  M     technician  43537
3      5  33  F          other  15213
4      6  42  M      executive  98101
5      7  57  M  administrator  91344
6      8  36  M  administrator  05201
7      9  29  M        student  01002
8     10  53  M         lawyer  90703
9     11  39  F          other  30329
10    12  28  F          other  06405
11    13  47  M       educator  29206
12    14  45  M      scientist  55106
13    15  49  F       educator  97301
14    16  21  M  entertainment  10309
15    17  30  M     programmer  06355
16    18  35  F          other  37212
17    19  40  M      librarian  02138
18    20  42  F      homemaker  95660
19    21  26  M         writer  30068
20    22  25  M         writer  40206
21    23  30  F         artist  48197
22    24  21  F         artist  94533
23    25  39  M       engineer  55107
24    26  49  M       engineer  21044
25    27  40  F      librarian  30030
26    28  32  M         writer  55369
27    29  41  M     programmer  94043
28    30   7  M        student  55436
29    31  24  M         artist  10003
..   ...  .. ..            ...    ...
912  914  44  F          other  08105
913  915  50  M  entertainment  60614
914  916  27  M       engineer  N2L5N
915  917  22  F        student  20006
916  918  40  M      scientist  70116
917  919  25  M          other  14216
918  920  30  F         artist  90008
919  921  20  F        student  98801
920  922  29  F  administrator  21114
921  923  21  M        student  E2E3R
922  924  29  M          other  11753
923  925  18  F       salesman  49036
924  926  49  M  entertainment  01701
925  927  23  M     programmer  55428
926  928  21  M        student  55408
927  929  44  M      scientist  53711
928  930  28  F      scientist  07310
929  931  60  M       educator  33556
930  932  58  M       educator  06437
931  933  28  M        student  48105
932  934  61  M       engineer  22902
933  935  42  M         doctor  66221
934  936  24  M          other  32789
935  937  48  M       educator  98072
936  938  38  F     technician  55038
937  939  26  F        student  33319
938  940  32  M  administrator  02215
939  941  20  M        student  97229
940  942  48  F      librarian  78209
941  943  22  M        student  77841

[942 rows x 5 columns]

In [69]:
df_user1.to_excel('structured1_file.xlsx',index=False)