In [1]:
print("Hello Adi")

Hello Adi


Intro

In [10]:
num = 20 
print(num)
num = num + 2
print(num)
num = num * 2
print(num)
num = num - 2
print(num)
num = num / 2
print(num ," - ")
num = num // 2
print(num)
num = num % 4
print(num)
num = num ** 2
print(num)

20
22
44
42
21.0  - 
10.0
2.0
4.0


In [22]:
num = 20 / (5 + 5) * 5 - 5 % 2
print(num)

9.0


In [23]:
print(num)

9.0


In [25]:
print(num < 1)

False


In [26]:
print(5666666666666666666666666666666666.0000000000000023444444)

5.666666666666666e+33


In [27]:
print(1232133333333333333333333333333333333333333333333333333333333333333333)

1232133333333333333333333333333333333333333333333333333333333333333333


In [28]:
num = 12333333333333333333333333333335332 + 243238597320590304845324235335
print(num)

12333576571930653923638178657570667


In [30]:
num = 'It was a number'
print(num)

It was a number


'Hello' "World"

In [33]:
num = "Hell'o World" "It's new"
print(num)

Hell'o WorldIt's new


Print Tax Amount Of A Person

In [40]:
name = "John"
salary = 100000
tax = 10
print(name, "has to pay tax of Rs.",(salary*10)/100)

John has to pay tax of Rs. 10000.0


In [48]:
pi = 3.14
radius = 5.5
area = pi * radius**2
print(area)

94.985


Round()

In [51]:
print(round(area, 2))

94.98


In [52]:
int(area)

94

In [53]:
float(area)

94.985

In [54]:
double(area)

NameError: name 'double' is not defined

In [56]:
''' Multiline Comments
    Multiline Comments
'''

' Multiline Comments\n    Multiline Comments\n'

Escaping

In [66]:
mystery='I Don\'t like to eat cheese'
print(mystery)
mystery="I Don't like to eat cheese"
print(mystery)
mystery="I Don't like to eat \"cheese\""
print(mystery)

I Don't like to eat cheese
I Don't like to eat cheese
I Don't like to eat "cheese"


String Concatenation & Formatting

In [78]:
firstName = "John"
lastName = "May"
fullName = firstName + " " + lastName
print({fullName})
print("My first name is {firstName} and last name is {lastName}".format(firstName=firstName,lastName=lastName))
print("My first name is {} and last name is {}".format(firstName,lastName))
print("My first name is", {firstName}, "and last name is ", {lastName})
print("My first name is", firstName, "and last name is ", lastName)

{'John Mayor'}
My first name is John and last name is Mayor
My first name is John and last name is Mayor
My first name is {'John'} and last name is  {'Mayor'}
My first name is John and last name is  Mayor


In [95]:
print(3 * "Hello \n")
print("Hello " * 3)

Hello 
Hello 
Hello 

Hello Hello Hello 


String Functions

In [115]:
print(fullName.capitalize())
print(fullName.upper())
print(fullName.replace('Mayor', 'mayer'))
print(fullName.lower())
len(fullName)
fullName.split(' ')
print(fullName.count('M'))
print(fullName.find('M'))
print(fullName.index('M'))
print(fullName.istitle())

John mayor
JOHN MAYOR
John mayer
john mayor
1
5
5
True


In [118]:
firstName > lastName

False

In [119]:
5<>5

SyntaxError: invalid syntax (<ipython-input-119-ec98f1eda3d0>, line 1)

In [120]:
5 and 5

5

In [121]:
True and False

False

In [122]:
True or False

True

In [124]:
True or False and True

True

In [127]:
False or True and False

False

In [135]:
pi = 3.14
radius = input("Enter the radius : ")
area = pi * int(radius)**2
print(area)
radius = input("Enter the radius : ")
area = pi * int(radius)**2
print(area)
radius = input("Enter the radius : ")
area = pi * int(radius)**2
print(area)


Enter the radius : 1
3.14
Enter the radius : 2
12.56
Enter the radius : 4
50.24


In [137]:
firstName[1:3]

'oh'

Ask Salary of an employee and ask the task slab & print the net salary as well as tax amount

In [140]:
salary = int(input("What is ur salary : "))
taxSlab = int(input("Which tax slab you belong : 10, 20, 30 : "))
taxAmt = (salary * taxSlab)/100
netSalary = salary - taxAmt
print("taxAmt - ", taxAmt, ", Net Salary : ", netSalary)

What is ur salary : 10000
Which tax slab you belong : 10, 20, 30 : 10
taxAmt -  1000.0 , Net Salary :  9000.0


In [142]:
9**(1/2)

3.0

In [171]:
print('Hello %d' %netSalary)

Hello\SHi9000


In [172]:
firstName[-1]

'n'

In [186]:
n = -1*len(firstName)
firstName[1:]

'ohn'

In [192]:
firstName.endswith('n')

True

Collaction

In [207]:
numbers = [[1,2,3],[5,6,7],[1]]
print(numbers)
numbers.reverse()
print(numbers)
print(numbers[1][1])
print(numbers[1:])

[[1, 2, 3], [5, 6, 7], [1]]
[[1], [5, 6, 7], [1, 2, 3]]
6
[[5, 6, 7], [1, 2, 3]]


In [223]:
dictionary = {"Fruits" : ["Apple","Orange","Banana"], "Drinks":["Coca"]}
print(dictionary)
print(dictionary.items())

{'Fruits': ['Apple', 'Orange', 'Banana'], 'Drinks': ['Coca']}
dict_items([('Fruits', ['Apple', 'Orange', 'Banana']), ('Drinks', ['Coca'])])


In [222]:
print(dictionary.get('Fruits')[2])

Banana


In [218]:
print(dictionary.get(1))

None


In [226]:
numbers + ["Veg"]

[[1], [5, 6, 7], [1, 2, 3], 'Veg']

In [235]:
dictionary.update({"Veg":"Potato"})

In [228]:
print(dictionary)

{'Fruits': ['Apple', 'Orange', 'Banana'], 'Drinks': ['Coca'], 'Veg': 'Potato'}


In [242]:
dictionary.popitem()

('Drinks', ['Coca'])

In [243]:
print(dictionary)

{'Fruits': ['Apple', 'Orange', 'Banana']}


In [6]:
txt = [1,2,3,0]
txt1 = txt.copy()
txt.reverse()
txt[1] = 5
print(txt)
print(txt1)

[0, 5, 2, 1]
[1, 2, 3, 0]


In [256]:
test1 = {1:'a',2:'b'}
test2 = test1.copy()
test2.update({1:'c'})
print(test2)
print(test1)

{1: 'c', 2: 'b'}
{1: 'a', 2: 'b'}


In [7]:
if txt[0]>0:
    print(txt[0])

In [262]:
tuple = (1,2,3,4,5)
tuple[0]

1

In [268]:
tuple[1:]

(2, 3, 4, 5)

In [264]:
max(tuple)

5

In [265]:
sum(tuple)

15

In [267]:
print(tuple[1] is str)

False


In [269]:
a = NaN

NameError: name 'Nan' is not defined

In [271]:
a = None
print(a)

None


In [295]:
set1 = {71,2,3,4,1,2,3,4,5}
set2 = set1
set2.add(6)
set2.issubset(set1)
set2.discard(1)
set3 = {10,20}
set2.union(set3)

{2, 3, 4, 5, 6, 10, 20, 71}

In [4]:
s = set()

In [11]:
x = 4
if x==1:
    print(x)
elif x==2:
    print(x)
else:
    if x==3:
        print(x)
    else:
        print(x)


4


In [24]:
salary = int(input("Enter ur salary : "))
if salary >= 10000 and salary <= 20000:
    tax = 3
elif salary >= 21000 and salary <= 30000:
    tax = 5
elif salary >= 31000 and salary <= 50000:
    tax = 10
else:
    tax = 20
print(tax)
taxAmount = (salary*tax)/100
netAmount = salary - taxAmount

print("Net Salary : ", netAmount, " and total tax : ", taxAmount)

Enter ur salary : 50000
10
Net Salary :  45000.0  and total tax :  5000.0


In [8]:
import numpy as np
array1 = np.arange(0,10)
array2 = np.arange(0,10)
array1 + array2
array1 - array2
array1 * array2
array1 / array2

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
1/array1

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
np.sin(array1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [13]:
np.sum(array1)

45

In [14]:
np.count_nonzero(array1)

9

In [16]:
np.log(array1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [30]:
array3 = np.arange(-40, 0, 2).reshape(2,10)
array4 = np.arange(-40, 0, 2).reshape(2,10)
array3 + array4

array([[-80, -76, -72, -68, -64, -60, -56, -52, -48, -44],
       [-40, -36, -32, -28, -24, -20, -16, -12,  -8,  -4]])

In [36]:
np.array(array1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
array5 = np.ones(10)

In [42]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [52]:
array7 = np.eye(4)
array8 = np.arange(0,16).reshape(4,4)
array7 / array7

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([[ 1., nan, nan, nan],
       [nan,  1., nan, nan],
       [nan, nan,  1., nan],
       [nan, nan, nan,  1.]])

In [53]:
np.random.rand(20)

array([0.61875218, 0.81001405, 0.35674383, 0.30210166, 0.55824777,
       0.00226645, 0.62452429, 0.47465352, 0.28618796, 0.09609755,
       0.37592911, 0.08161692, 0.77212029, 0.75244808, 0.60238046,
       0.96642779, 0.20472501, 0.55092617, 0.27247882, 0.42337736])

In [54]:
np.random.randn(20)

array([-0.99359149, -0.35215437, -0.00712242,  0.39370736, -0.13476774,
        2.24462178, -0.7127238 ,  0.99224245, -0.26567954, -0.65766649,
       -0.77609363,  0.65193247, -0.15792806, -0.49040931, -1.2332108 ,
        1.61658429,  0.78979267, -0.0950158 ,  0.95369437, -1.81162321])

In [55]:
np.random.randint(100)

11

In [58]:
np.random.randint(100,200,1)

array([107])

<B> Hi </B>

In [70]:
array10 = np.random.randint(1,100,10)
print(array10)

[95 24 59 64 41  1 16 19 18 12]


In [71]:
np.max(array10)

95

In [72]:
np.min(array10)

1

In [76]:
array10.argmin()

5

In [74]:
np.argmax(array10)

0

In [78]:
array10.squeeze()

array([95, 24, 59, 64, 41,  1, 16, 19, 18, 12])

In [80]:
array10.shape

(10,)

In [85]:
array10.reshape(2,5)
array10.reshape(2,5).shape

(2, 5)

In [88]:
array10.flatten()

array([95, 24, 59, 64, 41,  1, 16, 19, 18, 12])

In [89]:
array10.dtype

dtype('int32')

<b>GuessWord Game </b>

In [194]:
np.random.randint(0, 8)

4

In [12]:
import numpy as np
class GuessWordGame:

    def __init__(self, lifeline=5):
        self.lifeline = lifeline

    @staticmethod
    def getrandomfruit():
        fruits = ["APPLE", "ORANGE", "BANANA", "PINEAPPLE", "GRAPE", "MANGO", "KIWI", "GUAVA", "MELON"]
        #word = fruits[np.random.randint(0, 8)]
        return fruits[0]

    def decreaselifeline(self):
        if self.lifeline == 1:
            return False
        else:
            self.lifeline = self.lifeline - 1
            return True


game = GuessWordGame()
fruit = game.getrandomfruit()
#print(fruit)
length = len(fruit)
print("You have to guess a word of length - ", length)
i = 0
answer = ""
inp = ""
userinput = ""
while True:
    if len(answer) > 0:
        inp = "Your Input : " + answer + "."

    userinput = input(inp + "You have " + str(game.lifeline) + " lifeline left. Enter next character : ")
    if fruit[i] == userinput:
        i = i + 1
        answer = answer + userinput
        print("You have guessed it right")
    else:
        print("Your input is wrong. Please try again")
        if game.decreaselifeline():
            continue
        else:
            print("You don't have any life left. Thank you for trying")
            break
    if answer == fruit:
        print("You win")
        break



        
    

You have to guess a word of length -  5
You have 5 lifeline left. Enter next character : A
You have guessed it right
Your Input : A.You have 5 lifeline left. Enter next character : P
You have guessed it right
Your Input : AP.You have 5 lifeline left. Enter next character : P
You have guessed it right
Your Input : APP.You have 5 lifeline left. Enter next character : L
You have guessed it right
Your Input : APPL.You have 5 lifeline left. Enter next character : E
You have guessed it right
You win


In [2]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
np.ones(5) * 5

array([5., 5., 5., 5., 5.])

In [11]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.matrix(np.arange(0,9))

matrix([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [17]:
np.random.rand(25)

array([0.12940523, 0.46197655, 0.02585609, 0.68901781, 0.23385076,
       0.72010605, 0.39086914, 0.68918443, 0.10362248, 0.94902865,
       0.39768415, 0.55881995, 0.28569899, 0.70956263, 0.95228658,
       0.00800523, 0.86090801, 0.92356522, 0.94564316, 0.61338501,
       0.17083161, 0.29602255, 0.91952823, 0.51296705, 0.02160564])

In [25]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [29]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [75]:
array1 = np.arange(12,16)
array2 = np.arange(17,21)
array3 = np.arange(22,26)
array4 = np.append(np.append(array1,array2),array3).reshape(3,4)
array4[1,3]



20

In [81]:
array = np.arange(1,26).reshape(5,5)
array[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [88]:
array2 = array[1:,1]
print(array2.reshape(3,1))
array3 = array[1:,2]

array3 = np.concatenate((array2,array3),axis(1))
array3

ValueError: cannot reshape array of size 4 into shape (3,1)

In [91]:
array = np.arange(1,26).reshape(5,5)
array[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [92]:
np.sum(array)

325

In [107]:
array1 = np.arange(12,16)
array2 = np.arange(17,21)
array3 = np.arange(22,26)
array4 = np.append(array3,np.append(array1,array2)).reshape(3,4)
array4

array([[22, 23, 24, 25],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [108]:
np.sort(array4)

array([[22, 23, 24, 25],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

# array4.sum(2)

In [ ]:
label = ['a','a','c']
list1 = [10,20,30]
npArray = np.array(list1)
di1 = {'a':10,'b':20,'c':30}
di2 = {'c':30,'d':40,'e':50}

# PANDAS

In [114]:
import pandas as pd

In [130]:
pd.Series(data=list1, index=label)

a    10
a    20
c    30
dtype: int64

In [140]:
ser1 = pd.Series(di1)
ser2 = pd.Series(di2)

In [126]:
pd.Series(npArray)

0    10
1    20
2    30
dtype: int32

Ordered

In [141]:
ser1+ser2

a     NaN
b     NaN
c    60.0
d     NaN
e     NaN
dtype: float64

# DataFrames

In [181]:
df = pd.DataFrame(np.random.randn(5,4),['a','b','c','d','e'],[1,2,3,4])
df

1         2         3         4
a  0.342680 -1.266911  0.271005  2.140763
b  0.475369  0.246525 -1.084174 -2.381583
c -0.436349 -2.072412 -1.295440 -0.464024
d -0.057027  0.275930  1.494515  0.566821
e -2.303374  1.377001 -1.187387  0.079393

In [153]:
np.random.seed(100)

In [154]:
np.random.randn()

-1.7497654730546974

In [183]:
df[1]

a    0.342680
b    0.475369
c   -0.436349
d   -0.057027
e   -2.303374
Name: 1, dtype: float64

In [159]:
df[[1,3]]

1         3
a  0.907969  0.651118
b -0.848077 -2.018168
c  0.528813  0.188695
d -0.933237  0.190794
e  2.605967  0.302665

In [161]:
type(df)

pandas.core.frame.DataFrame

In [186]:
df[5]=df[1]+df[3]
df

1         2         3         4          6         5
a  0.342680 -1.266911  0.271005  2.140763   6.853608  0.613685
b  0.475369  0.246525 -1.084174 -2.381583   9.507381 -0.608805
c -0.436349 -2.072412 -1.295440 -0.464024  -8.726976 -1.731789
d -0.057027  0.275930  1.494515  0.566821  -1.140533  1.437489
e -2.303374  1.377001 -1.187387  0.079393 -46.067485 -3.490761

In [187]:
df[6]=df[1]*20
df

1         2         3         4          6         5
a  0.342680 -1.266911  0.271005  2.140763   6.853608  0.613685
b  0.475369  0.246525 -1.084174 -2.381583   9.507381 -0.608805
c -0.436349 -2.072412 -1.295440 -0.464024  -8.726976 -1.731789
d -0.057027  0.275930  1.494515  0.566821  -1.140533  1.437489
e -2.303374  1.377001 -1.187387  0.079393 -46.067485 -3.490761

In [191]:
df.drop('a',axis=0)

1         2         3         4          6         5
b  0.475369  0.246525 -1.084174 -2.381583   9.507381 -0.608805
c -0.436349 -2.072412 -1.295440 -0.464024  -8.726976 -1.731789
d -0.057027  0.275930  1.494515  0.566821  -1.140533  1.437489
e -2.303374  1.377001 -1.187387  0.079393 -46.067485 -3.490761

In [192]:
df

1         2         3         4          6         5
a  0.342680 -1.266911  0.271005  2.140763   6.853608  0.613685
b  0.475369  0.246525 -1.084174 -2.381583   9.507381 -0.608805
c -0.436349 -2.072412 -1.295440 -0.464024  -8.726976 -1.731789
d -0.057027  0.275930  1.494515  0.566821  -1.140533  1.437489
e -2.303374  1.377001 -1.187387  0.079393 -46.067485 -3.490761

In [266]:
df = pd.DataFrame(np.random.randint(1,100,20).reshape(5,4),['d','b','c','a','e'],[1,2,3,4])

In [196]:
np.random.randint(1,100, 20)

array([63, 51, 69, 36, 24, 10, 49, 22, 26, 55,  7, 38, 59, 40, 95, 52, 31,
       67, 25, 56])

In [199]:
np.random.rand(5,4)

array([[0.54937526, 0.27183085, 0.46060162, 0.69616156],
       [0.5003559 , 0.71607099, 0.52595594, 0.00139902],
       [0.39470029, 0.49216697, 0.40288033, 0.3542983 ],
       [0.50061432, 0.44517663, 0.09043279, 0.27356292],
       [0.9434771 , 0.02654464, 0.03999869, 0.28314036]])

In [200]:
df.loc['a']

1    0.254258
2    0.641101
3    0.200124
4    0.657625
Name: a, dtype: float64

In [202]:
df.iloc[1]

1    0.778289
2    0.779598
3    0.610328
4    0.309000
Name: b, dtype: float64

In [206]:
df.loc[['a','b'],[1,2]]

1         2
a  0.254258  0.641101
b  0.778289  0.779598

In [219]:
df.iloc[0:,1:]

2         3         4
a  0.641101  0.200124  0.657625
b  0.779598  0.610328  0.309000
c  0.859618  0.625324  0.982408
d  0.166694  0.023178  0.160745
e  0.953550  0.210978  0.360525

In [212]:
df[2:]

1         2         3         4
c  0.697735  0.859618  0.625324  0.982408
d  0.976500  0.166694  0.023178  0.160745
e  0.923497  0.953550  0.210978  0.360525

In [225]:
df>0

1     2     3     4
a  True  True  True  True
b  True  True  True  True
c  True  True  True  True
d  True  True  True  True
e  True  True  True  True

In [255]:
df[df>0]

1         2         3         4
d  0.582344  0.990893  0.992642  0.993117
b  0.110048  0.664481  0.523987  0.173150
c  0.942960  0.241860  0.998932  0.582694
a  0.183279  0.386845  0.189674  0.410771
e  0.594680  0.716586  0.486891  0.309590

In [250]:
df[(df[1]>0.5) | (df[2]>0.8)]

1         2         3         4
b  0.778289  0.779598  0.610328  0.309000
c  0.697735  0.859618  0.625324  0.982408
d  0.976500  0.166694  0.023178  0.160745
e  0.923497  0.953550  0.210978  0.360525

In [254]:
df.reset_index()

index         1         2         3         4
0     d  0.582344  0.990893  0.992642  0.993117
1     b  0.110048  0.664481  0.523987  0.173150
2     c  0.942960  0.241860  0.998932  0.582694
3     a  0.183279  0.386845  0.189674  0.410771
4     e  0.594680  0.716586  0.486891  0.309590

In [268]:
df.set_index(1)


2   3   4
1             
35   4  12  50
30  37  94  68
27  53  37  74
32  86  93  69
84  72  62  94

In [269]:
df

1   2   3   4
d  35   4  12  50
b  30  37  94  68
c  27  53  37  74
a  32  86  93  69
e  84  72  62  94

In [272]:
df.aggregate(sum,1)

d    101
b    229
c    191
a    280
e    312
dtype: int64

In [275]:
index1 = ['a1','a1','a1','c2','c2','c2']
index2 = [1,2,3,1,2,3]
hier_index = list(zip(index1,index2))
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['a1', 'c2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [284]:
df1 = pd.DataFrame(np.random.randn(6,2),hier_index,['num1', 'num2'])
df1

num1      num2
a1 1  0.749702  0.404251
   2 -0.567749 -1.136101
   3  0.212622 -1.080218
c2 1  0.376808  0.664850
   2  0.834378  0.274231
   3  1.100017  0.038378

In [294]:
df1.loc['c2'].loc[1]

num1    0.376808
num2    0.664850
Name: 1, dtype: float64

In [295]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
        'Person' :['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
        'Sales'  :[200,120,340,124,243,350]}

In [296]:
data

{'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
 'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
 'Sales': [200, 120, 340, 124, 243, 350]}

In [297]:
cmp = pd.DataFrame(data)

In [374]:
cmp['new'] = cmp['Sales'] * 5
cmp

Company   Person  Sales   new
0    GOOG      Sam    200  1000
1    GOOG  Charlie    120   600
2    MSFT      Amy    340  1700
3    MSFT  Vanessa    124   620
4      FB     Carl    243  1215
5      FB    Sarah    350  1750

In [309]:
grpCmp = cmp.groupby('Company')
grpCmp.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [310]:
grpCmp.count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [313]:
grpCmp.describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [315]:
grpCmp.describe().transpose()['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

In [322]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                   'B':['B0','B1','B2','B3'],
                   'C':['C0','C1','C2','C3'],
                   'D':['D0','D1','D2','D3']},[0,1,2,3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [323]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                   'B':['B4','B5','B6','B7'],
                   'C':['C4','C5','C6','C7'],
                   'D':['D4','D5','D6','D7']},[4,5,6,7])
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [324]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                   'B':['B8','B9','B10','B11'],
                   'C':['C8','C9','C10','C11'],
                   'D':['D8','D9','D10','D11']},[8,9,10,11])
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [325]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [326]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [355]:
df4 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                   'B':['B4','B5','B6','B7'],
                   'C':['C4','C5','C6','C7'],
                   'D':['D4','D5','D6','D7']})
df4

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [362]:
df5 = pd.DataFrame({'A':['A4','A4','A6','A7'],
                   'E':['B4','B5','B6','B7'],
                   'F':['C4','C5','C6','C7'],
                   'D':['D4','D5','D6','D7']})
df5

A   E   F   D
0  A4  B4  C4  D4
1  A4  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [363]:
pd.merge(df4,df5,how='inner',on='D')

A_x   B   C   D A_y   E   F
0  A4  B4  C4  D4  A4  B4  C4
1  A5  B5  C5  D5  A4  B5  C5
2  A6  B6  C6  D6  A6  B6  C6
3  A7  B7  C7  D7  A7  B7  C7

In [347]:
pd.merge(df4,df5,how='inner',on=['D','A'])

A   B   C   D   E   F
0  A4  B4  C4  D4  B4  C4
1  A5  B5  C5  D5  B5  C5
2  A6  B6  C6  D6  B6  C6
3  A7  B7  C7  D7  B7  C7

In [381]:
pd.merge(df4,df5,how='outer',on=['D'])

A_x   B   C   D A_y   E   F
0  A4  B4  C4  D4  A4  B4  C4
1  A5  B5  C5  D5  A4  B5  C5
2  A6  B6  C6  D6  A6  B6  C6
3  A7  B7  C7  D7  A7  B7  C7

In [360]:
df4.join(df5, how='inner')

A   B   C   D   H   E   F   I
0  A4  B4  C4  D4  A4  B4  C4  D4
1  A5  B5  C5  D5  A5  B5  C5  D5
2  A6  B6  C6  D6  A6  B6  C6  D6
3  A7  B7  C7  D7  A7  B7  C7  D7

In [366]:
df5['A'].unique()

array(['A4', 'A6', 'A7'], dtype=object)

In [367]:
df5['A'].nunique()

3

In [369]:
df5['A'].value_counts()

A4    2
A6    1
A7    1
Name: A, dtype: int64

In [370]:
def powerTo(x):
    return x**2

In [375]:
cmp['power'] = grpCmp['Sales'].apply(powerTo)

In [376]:
cmp

Company   Person  Sales   new   power
0    GOOG      Sam    200  1000   40000
1    GOOG  Charlie    120   600   14400
2    MSFT      Amy    340  1700  115600
3    MSFT  Vanessa    124   620   15376
4      FB     Carl    243  1215   59049
5      FB    Sarah    350  1750  122500

In [377]:
cmp.sort_values('Company')

Company   Person  Sales   new   power
4      FB     Carl    243  1215   59049
5      FB    Sarah    350  1750  122500
0    GOOG      Sam    200  1000   40000
1    GOOG  Charlie    120   600   14400
2    MSFT      Amy    340  1700  115600
3    MSFT  Vanessa    124   620   15376

In [383]:
pd.merge(df2,df3,how='outer',on=['D']).isnull()

A_x    B_x    C_x      D    A_y    B_y    C_y
0  False  False  False  False   True   True   True
1  False  False  False  False   True   True   True
2  False  False  False  False   True   True   True
3  False  False  False  False   True   True   True
4   True   True   True  False  False  False  False
5   True   True   True  False  False  False  False
6   True   True   True  False  False  False  False
7   True   True   True  False  False  False  False

In [384]:
pd.merge(df2,df3,how='outer',on=['D']).fillna('NULL')

A_x   B_x   C_x    D   A_y   B_y   C_y
0    A4    B4    C4   D4  NULL  NULL  NULL
1    A5    B5    C5   D5  NULL  NULL  NULL
2    A6    B6    C6   D6  NULL  NULL  NULL
3    A7    B7    C7   D7  NULL  NULL  NULL
4  NULL  NULL  NULL   D8    A8    B8    C8
5  NULL  NULL  NULL   D9    A9    B9    C9
6  NULL  NULL  NULL  D10   A10   B10   C10
7  NULL  NULL  NULL  D11   A11   B11   C11

In [398]:
excel = pd.read_excel('csv.xlsx', sheet_name='Sheet1')
excel

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [401]:
cmp.to_csv('cmp',index=False)

In [2]:
import pandas as pd
movieDate = pd.read_csv('u.user')
movieDate

1|24|M|technician|85711
0              2|53|F|other|94043
1             3|23|M|writer|32067
2         4|24|M|technician|43537
3              5|33|F|other|15213
4          6|42|M|executive|98101
5      7|57|M|administrator|91344
6      8|36|M|administrator|05201
7            9|29|M|student|01002
8            10|53|M|lawyer|90703
9             11|39|F|other|30329
10            12|28|F|other|06405
11         13|47|M|educator|29206
12        14|45|M|scientist|55106
13         15|49|F|educator|97301
14    16|21|M|entertainment|10309
15       17|30|M|programmer|06355
16            18|35|F|other|37212
17        19|40|M|librarian|02138
18        20|42|F|homemaker|95660
19           21|26|M|writer|30068
20           22|25|M|writer|40206
21           23|30|F|artist|48197
22           24|21|F|artist|94533
23         25|39|M|engineer|55107
24         26|49|M|engineer|21044
25        27|40|F|librarian|30030
26           28|32|M|writer|55369
27       29|41|M|programmer|94043
28           30|7|M|student|55436
29           31|24|M|artist|10003
..                            ...
912          914|44|F|other|08105
913  915|50|M|entertainment|60614
914       916|27|M|engineer|N2L5N
915        917|22|F|student|20006
916      918|40|M|scientist|70116
917          919|25|M|other|14216
918         920|30|F|artist|90008
919        921|20|F|student|98801
920  922|29|F|administrator|21114
921        923|21|M|student|E2E3R
922          924|29|M|other|11753
923       925|18|F|salesman|49036
924  926|49|M|entertainment|01701
925     927|23|M|programmer|55428
926        928|21|M|student|55408
927      929|44|M|scientist|53711
928      930|28|F|scientist|07310
929       931|60|M|educator|33556
930       932|58|M|educator|06437
931        933|28|M|student|48105
932       934|61|M|engineer|22902
933         935|42|M|doctor|66221
934          936|24|M|other|32789
935       937|48|M|educator|98072
936     938|38|F|technician|55038
937        939|26|F|student|33319
938  940|32|M|administrator|02215
939        941|20|M|student|97229
940      942|48|F|librarian|78209
941        943|22|M|student|77841

[942 rows x 1 columns]