PRINT NAME

In [2]:
print("Hello Anusha")

Hello Anusha


In [3]:
print('-------------------------')
print('Hello')

-------------------------
Hello


------------ OPERATORS ---------------------

In [5]:
2+10

12

EXPONENT

In [6]:
5**4

625

In [10]:
4**5

1024

INTEGRAL DIVISION

In [7]:
20//3

6

In [8]:
20/3

6.666666666666667

In [9]:
20%3

2

In [11]:
5+5-10

0

In [12]:
5*5/10

2.5

In [17]:
(5+5)/10*5-2

3.0

In [16]:
5+5/10*5-2

5.5

In [14]:
(2**2)-4+(3**2)

9

VARIABLE ASSIGNMENT

No need to declare any datatype. Automatically datatype will be assigned

In [18]:
a=5

In [19]:
a

5

In [20]:
b=3

Integer addition

In [21]:
a+b

8

In [22]:
c=3.5

Interger + decimal = decimal

In [23]:
a+c

8.5

In [29]:
d=10.0

In [30]:
a*d

50.0

In [31]:
b/d

0.3

String assigment

In [32]:
a="Hello Anusha"

In [33]:
a

'Hello Anusha'

In [34]:
print(a)

Hello Anusha


In [35]:
b='Hello Anusha'

In [36]:
b

'Hello Anusha'

In [37]:
print(b)

Hello Anusha


In [38]:
"Hello let's try this one"

"Hello let's try this one"

In [39]:
c="Hello let's try this one"

In [40]:
c

"Hello let's try this one"

In [41]:
print(c)

Hello let's try this one


Calculate tax of a person

In [42]:
P_Income=10000

In [ ]:
tax_percent=0.1

In [47]:
Tax_person=P_Income*tax_percent

In [48]:
Tax_person

1000.0

In [55]:
print("Tax amount of the person",Tax_person,"whose salary is",P_Income)


Tax amount of the person is 1000.0 whose salary is 10000


In [78]:
Salary=P_Income-Tax_person

In [82]:
print("Total salary of the person is Rs.",int(Salary))

Total salary of the person is Rs. 9000


Area of the circle

In [56]:
Pi_val=3.14

In [57]:
r=10

In [61]:
Area=Pi_val*r**2

In [63]:
Area

314.0

In [65]:
print("Area of the circle is",Area)

Area of the circle is 314.0


ROUND FUNCTION (rounding a number)

In [66]:
num=7/2

In [67]:
num

3.5

In [68]:
round(num,2)

3.5

In [69]:
round(num,0)

4.0

In [70]:
num1=7/3

In [71]:
num1

2.3333333333333335

In [72]:
round(num1,0)

2.0

In [73]:
round(num1,3)

2.333

CONVERT VALUE INTO INT,FLOAT

In [74]:
int(Area)

314

In [75]:
int(num1)

2

In [76]:
float(Area)

314.0

ESCAPING (\)

In [84]:
Mystory='I don't like to eat cheese'
print(Mystory)

SyntaxError: invalid syntax (<ipython-input-84-4e113e135809>, line 1)

In [86]:
Mystory="I don't like to eat "cheese""
print(Mystory)

SyntaxError: invalid syntax (<ipython-input-86-ba6118219686>, line 1)

In [87]:
Mystory='I don\'t like to eat cheese'
print(Mystory)

I don't like to eat cheese


In [89]:
Mystory="I don't like to eat \"cheese\""
print(Mystory)

I don't like to eat "cheese"


STRING CONCATENATION (+)

In [90]:
a="Anusha"

In [91]:
b="Koila"

In [92]:
a+b

'AnushaKoila'

In [93]:
a +b

'AnushaKoila'

In [94]:
a+' '+b 

'Anusha Koila'

In [95]:
print(a+' '+b)

Anusha Koila


FORMATTED STATEMENTS

In [97]:
name="Anusha"
Age=27

In [101]:
print("My name is {one} and my age is {two}".format(one=name,two=Age))

My name is Anusha and my age is 27


In [102]:
print("My name is {one} and my age is {two}".format(one='Anusha',two=27))

My name is Anusha and my age is 27


WITHOUT USING THE RUNTIME VARIABLES

In [104]:
print("My name is and my age is ".format(name,Age))

My name is and my age is 


In [105]:
print("My name is {} and my age is {}".format(name,Age))

My name is Anusha and my age is 27


REPLICATION

In [109]:
print(3* "Hello")

HelloHelloHello


In [110]:
print(100 * "Hi" + "\nTHE END")

HiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHiHi
THE END


In [113]:
print(10 * "Hi \n" , "\nTHE END")

Hi 
Hi 
Hi 
Hi 
Hi 
Hi 
Hi 
Hi 
Hi 
Hi 
 
THE END


In [114]:
print("Hello" *3)

HelloHelloHello


METHODS AND FUNCTIONS

In [116]:
#UPPER
"anusha".upper()

'ANUSHA'

In [118]:
#length
len("Hello Anusha")

12

In [119]:
"Hello my name is Anusha".replace("name","first name")

'Hello my first name is Anusha'

In [133]:
Bob="My name is Anusha "*30
print(Bob)
Bob1=Bob.replace("Anusha","Anusha Koila \n")
print(Bob1)
print("Length of Bob1 is ",len(Bob))

My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha 
My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha Koila 
 My name is Anusha

In [136]:
Bob.split()

['My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name',
 'is',
 'Anusha',
 'My',
 'name'

In [137]:
Bob.isdigit()

False

In [138]:
Bob.swapcase()

'mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA mY NAME IS aNUSHA '

In [139]:
Bob.format()

'My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha My name is Anusha '

COMPARISON OPERATORS

In [140]:
2>3

False

In [141]:
a="Anusha"
b="koila"
a!=b

True

In [142]:
101.567<=100

False

In [143]:
5<>5

SyntaxError: invalid syntax (<ipython-input-143-ec98f1eda3d0>, line 1)

In [144]:
a==b

False

LOGICAL OPERATOR (AND,OR)

In [145]:
(5==6) AND (6!=4) OR (9>3)

SyntaxError: invalid syntax (<ipython-input-145-cac8f3d0b0a1>, line 1)

In [146]:
(5==6) and (6!=4) or (9>3)

True

In [147]:
(5==6) and (6!=4) or (9<3)

False

ACCEPTING INPUT

In [2]:
age=input("Enter your age ")

Enter your age 27


Area of the circle with different input value

In [9]:
Pi_val=3.14
r=input("Enter radius : ")
Area=Pi_val*int(r)**2
print("Area of the circle is : " ,Area)

Enter radius : 7
Area of the circle is :  153.86


Net Income of an employee (input Salary and tax slab). print net salary and tax amount

In [172]:
salary =input("Enter Salary of an employee :")
tax_percent=input("Enter tax slab :")
salary=int(salary)
tax_percent=int(tax_percent)
tax_amount=salary*(tax_percent/100)
net_salary=salary-tax_amount
print("Employee Net Salary : ",net_salary)
print("Emplyoee Tax amount : ",tax_amount)

Enter Salary of an employee :50000
Enter tax slab :10
Employee Net Salary :  45000.0
Emplyoee Tax amount :  5000.0


CONVERSION FORMAT METHODS

In [21]:
s='Hi Anusha'
print("String is :%s" %(s))

String is :Hi Anusha


In [27]:
s=1234.6
print("String is :%3F" %(s))

String is :1234.600000


In [28]:
var1=3
print('Value of var1 is %s'%(var1))

Value of var1 is 3


In [29]:
var1=3
print('Value of var1 is %s'+var1)

TypeError: must be str, not int

In [30]:
var1="anusha"
print('Value of var1 is %s'%(var1))

Value of var1 is anusha


In [171]:
num1=10
num2=20
n=num1+num2
print("The addition of %s and %s is %s "%(num1,num2,n))

The addition of 10 and 20 is 30 


In [33]:
print("Hi my name is Anusha\nI am from societe generale\nWorking in ITEC/DCC.")

Hi my name is Anusha
I am from societe generale
Working in ITEC/DCC.


INDEXING

In [37]:
var="Hello Anusha"
var[5]

' '

In [38]:
var[7]

'n'

In [39]:
var[-1] #Left to right index will start from 0 and right to left it will start from -1

'a'

In [40]:
var[-6]

'A'

In [41]:
var[:]

'Hello Anusha'

In [42]:
var[4:]

'o Anusha'

In [43]:
var[-4:]  # colun doesnt work with '-'

'usha'

In [53]:
var[-6:-4]

'An'

In [47]:
var[0:2] #UPPER BOUNDARY IS EXCLUDED AND LOWER BOUNDARY IS INCLUDED

'He'

In [49]:
var[2:8]

'llo An'

In [54]:
var.isalpha()

False

In [55]:
var.isprintable()

True

COLLECTIONS

In [ ]:
#LIST   --- can have duplicates
#MAP
#DICTIONARY
#SET -- cannot have duplicates

In [56]:
#LIST OF NUMBERS
z=[1,2,3]
z

[1, 2, 3]

In [57]:
x=[1,2,"Anusha"]
x

[1, 2, 'Anusha']

In [59]:
y=[1,x]
y

[1, [1, 2, 'Anusha']]

In [60]:
z[0]

1

In [61]:
y[0]

1

In [65]:
y[1]

[1, 2, 'Anusha']

In [66]:
y[2]

IndexError: list index out of range

In [67]:
y[1][0]

1

In [68]:
y[1][2]

'Anusha'

In [70]:
y[1:]

[[1, 2, 'Anusha']]

In [78]:
y[0:1]

[1]

In [77]:
y[1][1:]

[2, 'Anusha']

In [73]:
# DICTIONARY
# {key,value}
# ex: {1:'Ram'}

In [86]:
d={1:'Anu'}
d[1]

'Anu'

In [88]:
d[1]

'Anu'

In [148]:
d.keys()

dict_keys([1])

In [122]:
y={'x':[1,2,3]}
y['x'][1]

2

In [116]:
#append to list
mylst=[1,2,3,'Hello']
mylst=mylst+['Bangalore']
mylst

[1, 2, 3, 'Hello', 'Bangalore']

In [112]:
2*mylst

[1, 2, 3, 'Hello', 'Bangalore', 1, 2, 3, 'Hello', 'Bangalore']

In [117]:
mylst
mylst.append('Hi')
mylst

[1, 2, 3, 'Hello', 'Bangalore', 'Hi']

In [ ]:
#Reverse a list

In [95]:
new_list=['a','b','c','d','e']
new_list

['a', 'b', 'c', 'd', 'e']

In [96]:
new_list.reverse()

In [97]:
new_list

['e', 'd', 'c', 'b', 'a']

In [102]:
#Sort

In [103]:
new_list.sort()
new_list

['a', 'b', 'c', 'd', 'e']

In [104]:
new_list

['a', 'b', 'c', 'd', 'e']

In [123]:
#NESTED LIST
LIST=[[1,2,3],[4,5,6],[7,8,9]]

In [124]:
LIST

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [125]:
#TUPLES
tup1=(1,2,3,4,5)
len(tup1)

5

In [127]:
list1=[1,2,3]
list1

[1, 2, 3]

In [128]:
list1[0]='Hello'  # we can change value of List
list1

['Hello', 2, 3]

In [129]:
tup1

(1, 2, 3, 4, 5)

In [130]:
tup1[0]='Hello'  #we cannot change value of a tuple
tup1

TypeError: 'tuple' object does not support item assignment

In [131]:
max(tup1)

5

In [132]:
#addition of tuples
tup1

(1, 2, 3, 4, 5)

In [133]:
tup2=(1,2,3)
tup1+tup2

(1, 2, 3, 4, 5, 1, 2, 3)

In [134]:
4 in tup1  #checking of value in a tuple

True

In [135]:
4 in tup2

False

In [136]:
tup1[1:4]

(2, 3, 4)

In [138]:
#SET - UNORDERED SET OF DISTINCT ELEMENTS .CLOSED BY {}
set1={1,2,3}
set1

{1, 2, 3}

In [139]:
min(set1)

1

In [140]:
set2={4,5,6}
set1.update(set2)           #append will not work here. Only update can be used

In [141]:
set1

{1, 2, 3, 4, 5, 6}

In [142]:
set3={1,2,7,8,9}
set1.update(set3)                #NO DUPLICATES ARE ALLOWED

In [143]:
set1        

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [145]:
set4={1,1,1,2,3,3,3,4}
set4

{1, 2, 3, 4}

In [149]:
# we cannot acccess particular element in set

In [150]:
x=set()
x.add(1)

In [151]:
x

{1}

In [152]:
x.add(2)
x

{1, 2}

In [153]:
l=[1,1,2,2,3,4,4,5,5]        #LIST
l

[1, 1, 2, 2, 3, 4, 4, 5, 5]

In [154]:
set(l)           #SET GIVES DISTINCT VALUES

{1, 2, 3, 4, 5}

CONDITIONAL STATEMENTS (IF ELSE)

In [160]:
#IF ELSE
a=10
if(a>5):
    print ("a is greater than 5")
else:
    print ("a is lesses than 5")


a is greater than 5


In [163]:
#IF ELIF

a=input("Enter value of a :")
b=input("Enter value of b :")
if(a>b):
    print("a is greater than b")
elif(a<b):
    print("a is lesser than b")
else:
    print("a and b are equal")


Enter value of a :10
Enter value of b :10
a and b are equal


In [164]:
#Tax Computation
# 10k -20k --> 3%
#21 -30k --> 5%
#31 - 50k --> 10%
# >51k  --> 20%

In [169]:
salary=input("Enter Salary of an employee")
salary=int(salary)
if(salary>=10000 and salary<=20000):
    tax=int(salary)*(3/100)
elif(salary>20000 and salary<=30000):
    tax=int(salary)*(5/100)
elif(salary>30000 and salary<=50000):
    tax=int(salary)*(10/100)
else:
    tax=int(salary)*(20/100)

net=salary-tax
print("Total Payable tax : %s"%(tax))
print("Net Income :%s "%(net))


Enter Salary of an employee11000
Total Payable tax : 330.0
Net Income :10670.0 


LOOPS

In [174]:
#Student Grading

name=input("Enter name of student :")
mark=input("Enter mark of an student :")
mark=int(mark)
if(mark>=90 and mark<=100):
    grade='A+'
elif(mark>=80 and mark<90):
    grade = 'A'
elif(mark>=70 and mark<80):
    grade = 'B'
elif(mark>=60 and mark<70):
    grade = 'C'
else:
    grade='FAIL'

print("Name of the student : %s"%(name))
print("Marks  :%s "%(mark))
print("Grade  :%s "%(grade))

Enter name of student :Anusha
Enter mark of an student :92
Name of the student : Anusha
Marks  :92 
Grade  :A+ 


In [175]:
#Input : LOAN AMOUNT, RATE OF INTEREST , LOAN PERIOD
#CALCULATE SIMPLE INTEREST, TOTAL PAYABLE AMOUNT

loan_amt=input("Enter Loan Amount you need :")
loan_period=input("Enter period you want to pay the loan :")
rate_interest=input("Enter rate of interest :")

loan_amt=int(loan_amt)
loan_period=int(loan_period)
rate_interest=int(rate_interest)

SI=(loan_amt*rate_interest*loan_period)/100

Total_amt=loan_amt+SI

EMI=Total_amt/loan_period

print("Total Payable Amount is : %s"%(Total_amt))
print("EMI per year is : %s"%(EMI))
print("EMI per month is : %s"%(EMI/12))

CI=loan_amt*((1+(rate_interest/100))**loan_period)

print("Compound interest : %s"%(CI))

Enter Loan Amount you need :4500000
Enter period you want to pay the loan :10
Enter rate of interest :8
Total Payable Amount is : 8100000.0
EMI per year is : 810000.0
EMI per month is : 67500.0
Compound interest : 9715162.487727547


LOOPING

In [176]:
var=int(input("Enter range of numbers you want to print"))
for i in range(0,var):
    print(i)

Enter range of numbers you want to print10
0
1
2
3
4
5
6
7
8
9


In [177]:
list1=[1,2,3,4,5,6,7,8,9,10]
for i in list1:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [178]:
#print *

count=int(input("Enter no of lines star should be printed :"))

while(count!=0):
    print('*'*count)
    count=count-1

Enter no of lines star should be printed :10
**********
*********
********
*******
******
*****
****
***
**
*


FUNCTIONS

In [182]:
#def functionname(arg1,arg2);
#var=functionname(arg1,arg2)

num1=int(input("Enter value of a"))
num2=int(input("Enter value of b"))
def addition(a,b):
    c=a+b
    return c
add=addition(num1,num2)
print("Addition of a and b is : %s"%add)

Enter value of a10
Enter value of b20
Addition of a and b is : 30


In [13]:
#print odd numbers
#raise exception when negtive numbers are inputted

try:
    num = int(input("Enter an number :"))
except erro1:
    if(num<0):
        print("Negative numbers not allowed")
else:
    print("ODD numbers list :\n ")
    for i in range(1,num):
        res=i%2
        if(res!=0):
            print(i)
            i=i+1



Enter an number :20
ODD numbers list :
 
1
3
5
7
9
11
13
15
17
19


In [1]:
##lambda functions

OOP

In [2]:
#class

class Person:
    print("Hello")

Hello


In [3]:
#creating object and instance variable
person1=Person()
person1.name="Amar"
print(person1.name)

Amar


In [4]:
#creating class and class variable
class Dog:
    doginfo="Dog is pet animal"
    
dog1=Dog()
print(dog1.doginfo)
    

Dog is pet animal


In [6]:
class Dog:
    def __init__(self,name,age,teeth):
        self.name=name
        self.age=age
        self.teeth=teeth
dog1=Dog("Sony","5","4")
print(dog1.name)
print(dog1.age)

Sony
5


In [16]:
#read and write into a file
file=open("fun1.txt","w")
file.write("Hellooo How are you\n I am doing good")

36

In [17]:
#
file=open("fun.txt","r")
print(file.read())

Hellooo How are you
 I am doing good


In [18]:
d={('Hi',1),('Hi',1)}
d

{('Hi', 1)}

In [24]:
d={'Karnataka': 1, 'were': 1, 'formed': 1}
d.keys()

dict_keys(['Karnataka', 'were', 'formed'])

NUMPY

In [94]:
#IMPORT NUMPY LIBRARY
import numpy as np
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [34]:
arr/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
1/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [36]:
#scalar multiplication

In [37]:
3*arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [38]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [39]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [41]:
np.average(arr)

4.5

In [42]:
np.sum(arr)

45

In [43]:
ab=np.exp(arr)

In [44]:
ab

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [49]:
np.count_nonzero(ab)

10

In [50]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [51]:
np.sin(arr)+np.cos(arr)

array([ 1.        ,  1.38177329,  0.49315059, -0.84887249, -1.41044612,
       -0.67526209,  0.68075479,  1.41088885,  0.84385821, -0.49901178])

In [52]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [55]:
np.sin(np.exp(arr))+np.cos(np.exp(arr))

array([ 1.38177329, -0.50095262,  1.3422112 ,  1.27306576, -1.29942967,
       -1.41369453,  1.2276078 , -1.19209401, -0.51398072, -1.40208224])

In [56]:
#ARRAY OF LIST IS MATRIX

In [58]:
my_matrix=([1,2,3],[1,2,3],[4,5,6])
my_matrix

([1, 2, 3], [1, 2, 3], [4, 5, 6])

In [59]:
np.array(my_matrix)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [62]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [65]:
np.arange(0,5,3)

array([0, 3])

In [67]:
#create matrix of zeroes
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.twos((5,5))

AttributeError: module 'numpy' has no attribute 'twos'

In [72]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
#random numbers
np.random.rand(2)

array([0.43846146, 0.15377067])

In [75]:
np.random.rand(5,5)

array([[0.8554325 , 0.44991651, 0.55673672, 0.70337949, 0.16845387],
       [0.27880152, 0.38064868, 0.86702644, 0.44898339, 0.21846085],
       [0.75581151, 0.33277251, 0.45012909, 0.28842123, 0.07133271],
       [0.29651802, 0.17343001, 0.61101225, 0.15844481, 0.35346147],
       [0.8364043 , 0.95708172, 0.65235388, 0.1578584 , 0.74611836]])

In [76]:
np.random.rand(10,10)

array([[5.74687579e-01, 5.74578496e-01, 8.62308803e-01, 7.37204379e-01,
        6.92904314e-01, 1.02361618e-01, 9.16309409e-01, 6.63598378e-01,
        3.97937971e-01, 5.48457080e-01],
       [5.32542045e-01, 9.30464071e-01, 5.58491572e-01, 8.47688639e-01,
        5.66681254e-01, 3.98182345e-01, 7.74435387e-01, 3.48585604e-02,
        9.52624534e-01, 4.01448474e-01],
       [2.70883426e-02, 8.24953447e-01, 3.03777903e-01, 4.63234631e-01,
        9.16155178e-01, 3.87331033e-01, 4.95788574e-01, 6.54383483e-01,
        9.85127771e-01, 5.90270614e-01],
       [9.94321618e-01, 5.93011634e-01, 8.20834760e-01, 6.07454913e-01,
        9.16396061e-01, 7.42303021e-01, 5.84176450e-01, 9.82863599e-01,
        8.29678708e-01, 3.00865200e-02],
       [4.33123600e-01, 7.69829051e-01, 8.02267682e-02, 6.43599591e-01,
        4.36306429e-01, 4.84910472e-01, 1.27294960e-01, 2.97725016e-01,
        9.43041902e-01, 5.98290714e-01],
       [1.01807662e-01, 3.28306476e-01, 1.93330503e-01, 7.65146274e-01,
   

In [85]:
arr=np.arange(25)
ranarr=np.random.randint(5,10,50)
ranarr

array([6, 5, 8, 7, 5, 6, 7, 7, 5, 6, 5, 9, 6, 5, 5, 7, 9, 8, 8, 6, 5, 7,
       6, 9, 6, 6, 6, 7, 9, 5, 7, 8, 6, 8, 7, 6, 8, 7, 9, 8, 6, 7, 6, 5,
       8, 8, 8, 5, 9, 5])

In [94]:
ranarr.reshape(10,5)

array([[6, 5, 8, 7, 5],
       [6, 7, 7, 5, 6],
       [5, 9, 6, 5, 5],
       [7, 9, 8, 8, 6],
       [5, 7, 6, 9, 6],
       [6, 6, 7, 9, 5],
       [7, 8, 6, 8, 7],
       [6, 8, 7, 9, 8],
       [6, 7, 6, 5, 8],
       [8, 8, 5, 9, 5]])

In [93]:
ranarr.shape  #vector

(50,)

In [95]:
ranarr.dtype

dtype('int32')

In [96]:
list=['A','N','U','S','H','A']
len(list)

6

In [1]:
##GUESS THE WORD

Word="ANUSHA"

list=['A','N','U','S','H','A']
a=10
print("---- Guess the word ---")
print("You have %s attempts left"%(a))

word_len=len(list)
i=0
while(i!=word_len and a>0):
    w1=input("Enter the %s letter :"%(i+1))
    w1=w1.upper()
    if(list[i]==w1):
        print("You got it right..!!!")
        i=i+1
    else:
        print("Wrong... Try again")
        a=a-1
        print("You are left with %s attempts"%(a))
        continue;
if(a>0):
    print(" **  CONGRATULATIONS ** ")
else:
    print("Sorry... You lost the game ")


---- Guess the word ---
You have 10 attempts left
Enter the 1 letter :a
You got it right..!!!
Enter the 2 letter :u
Wrong... Try again
You are left with 9 attempts
Enter the 2 letter :n
You got it right..!!!
Enter the 3 letter :u
You got it right..!!!
Enter the 4 letter :s
You got it right..!!!
Enter the 5 letter :9
Wrong... Try again
You are left with 8 attempts
Enter the 5 letter :0
Wrong... Try again
You are left with 7 attempts
Enter the 5 letter :0
Wrong... Try again
You are left with 6 attempts
Enter the 5 letter :8
Wrong... Try again
You are left with 5 attempts
Enter the 5 letter :9
Wrong... Try again
You are left with 4 attempts
Enter the 5 letter :h
You got it right..!!!
Enter the 6 letter :a
You got it right..!!!
 **  CONGRATULATIONS ** 


In [3]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [18]:
arr=np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [19]:
arr.shape

(10,)

In [20]:
arr.reshape(2,5)

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
arr=np.random.randint(1,8,9)

In [14]:
arr.reshape(3,3)

array([[7, 4, 7],
       [3, 1, 5],
       [2, 2, 4]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.rand()

0.6662867020720439

In [25]:
arr=np.random.rand(25)
arr

array([0.4909226 , 0.37993081, 0.54024807, 0.82467763, 0.74942674,
       0.12988085, 0.27141463, 0.25742416, 0.99519714, 0.86684072,
       0.62780766, 0.65705587, 0.45543444, 0.02541013, 0.22864854,
       0.59120036, 0.27864997, 0.16074863, 0.64462058, 0.70851266,
       0.75268013, 0.34725315, 0.85957003, 0.1347195 , 0.49366586])

In [27]:
np.random.randn(10)

array([ 0.11834716,  0.83847097,  0.49945193,  0.71210693, -1.54571626,
       -0.04396935, -1.25848437, -1.01027926, -1.7066218 , -0.45133677])

In [30]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [33]:
np.random.rand(0,1)

array([], shape=(0, 1), dtype=float64)

In [41]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [51]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
mat.shape

(5, 5)

In [53]:
mat[0][1]

2

In [63]:
mat[:2,:2]

array([[1, 2],
       [6, 7]])

In [66]:
mat[:2,2:3]

array([[3],
       [8]])

In [67]:
mat[0:4,1:5]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [68]:
mat=np.arange(1,26).reshape(5,5)

In [69]:
mat.shape

(5, 5)

In [70]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
mat1=mat[2:,1:]
mat1

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [74]:
mat2=mat[3:4,4:]
mat2

array([[20]])

In [76]:
mat3=mat[:3,1:2]
mat3

array([[ 2],
       [ 7],
       [12]])

In [79]:
mat4=mat[4:]
mat4

array([[21, 22, 23, 24, 25]])

In [80]:
mat5=mat[3:]
mat5

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [81]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [82]:
mat.sum()

325

In [83]:
mat.max()

25

In [84]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [85]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

# PANDAS LIBRARY

In [ ]:
#Build on top of NUMPY

In [90]:
d={'a':10,'b':20,'c':30}
d

{'a': 10, 'b': 20, 'c': 30}

In [91]:
d.values()

dict_values([10, 20, 30])

In [92]:
d.keys()

dict_keys(['a', 'b', 'c'])

In [6]:
import pandas as pd

In [94]:
labels=['a','b','c']
my_list=[10,15,20]

In [95]:
pd.Series(data=my_list)

0    10
1    15
2    20
dtype: int64

In [96]:
pd.Series(data=my_list,index=labels)

a    10
b    15
c    20
dtype: int64

In [97]:
pd.Series(my_list,labels)

a    10
b    15
c    20
dtype: int64

In [99]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [103]:
ser1=pd.Series([1,2,3,4],index=['A','B','C','D'])
ser1

A    1
B    2
C    3
D    4
dtype: int64

In [104]:
ser2=pd.Series([1,2,5,4],index=['A','B','E','D'])
ser2

A    1
B    2
E    5
D    4
dtype: int64

In [105]:
ser2['E']

5

In [106]:
ser1+ser2  #common index , it will join . If index are not matching, values will not be joined (NaN)

A    2.0
B    4.0
C    NaN
D    8.0
E    NaN
dtype: float64

In [107]:
ser1-ser2

A    0.0
B    0.0
C    NaN
D    0.0
E    NaN
dtype: float64

In [108]:
ser1*ser2

A     1.0
B     4.0
C     NaN
D    16.0
E     NaN
dtype: float64

In [109]:
ser1/ser2

A    1.0
B    1.0
C    NaN
D    1.0
E    NaN
dtype: float64

Index and values are ordered pair

In [110]:
#DataFrame --> it will have both rows and columns

In [8]:
from numpy.random import randn

In [9]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [10]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [14]:
r=np.random.seed(101)

In [15]:
r

In [13]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [17]:
df[['W','Z']]df['W']

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [18]:
df['new']=df['X']+df['Y']

In [19]:
df['new']

A    1.536102
B   -1.167395
C    1.268936
D   -1.692109
E    4.584725
Name: new, dtype: float64

In [20]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  1.536102
B  0.651118 -0.319318 -0.848077  0.605965 -1.167395
C -2.018168  0.740122  0.528813 -0.589001  1.268936
D  0.188695 -0.758872 -0.933237  0.955057 -1.692109
E  0.190794  1.978757  2.605967  0.683509  4.584725

In [21]:
df['new']=df['Y']-df['Z']

In [22]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  0.404144
B  0.651118 -0.319318 -0.848077  0.605965 -1.454042
C -2.018168  0.740122  0.528813 -0.589001  1.117814
D  0.188695 -0.758872 -0.933237  0.955057 -1.888294
E  0.190794  1.978757  2.605967  0.683509  1.922458

In [23]:
df['res']=df['new']*5

In [24]:
df

W         X         Y         Z       new       res
A  2.706850  0.628133  0.907969  0.503826  0.404144  2.020718
B  0.651118 -0.319318 -0.848077  0.605965 -1.454042 -7.270212
C -2.018168  0.740122  0.528813 -0.589001  1.117814  5.589070
D  0.188695 -0.758872 -0.933237  0.955057 -1.888294 -9.441469
E  0.190794  1.978757  2.605967  0.683509  1.922458  9.612292

In [25]:
df['sal']=df['W']+df['W']*0.2   #20% hike in salary
df

W         X         Y         Z       new       res       sal
A  2.706850  0.628133  0.907969  0.503826  0.404144  2.020718  3.248220
B  0.651118 -0.319318 -0.848077  0.605965 -1.454042 -7.270212  0.781342
C -2.018168  0.740122  0.528813 -0.589001  1.117814  5.589070 -2.421802
D  0.188695 -0.758872 -0.933237  0.955057 -1.888294 -9.441469  0.226434
E  0.190794  1.978757  2.605967  0.683509  1.922458  9.612292  0.228953

In [29]:
#delete new column
df1=df.drop('new',axis=1)
df1

W         X         Y         Z       res       sal
A  2.706850  0.628133  0.907969  0.503826  2.020718  3.248220
B  0.651118 -0.319318 -0.848077  0.605965 -7.270212  0.781342
C -2.018168  0.740122  0.528813 -0.589001  5.589070 -2.421802
D  0.188695 -0.758872 -0.933237  0.955057 -9.441469  0.226434
E  0.190794  1.978757  2.605967  0.683509  9.612292  0.228953

In [30]:
#delete E row
df2=df.drop('E',axis=0)
df2

W         X         Y         Z       new       res       sal
A  2.706850  0.628133  0.907969  0.503826  0.404144  2.020718  3.248220
B  0.651118 -0.319318 -0.848077  0.605965 -1.454042 -7.270212  0.781342
C -2.018168  0.740122  0.528813 -0.589001  1.117814  5.589070 -2.421802
D  0.188695 -0.758872 -0.933237  0.955057 -1.888294 -9.441469  0.226434

In [33]:
#delete res column and delete permanently 
df.drop('res',axis=1,inplace=True)
df

W         X         Y         Z       new       sal
A  2.706850  0.628133  0.907969  0.503826  0.404144  3.248220
B  0.651118 -0.319318 -0.848077  0.605965 -1.454042  0.781342
C -2.018168  0.740122  0.528813 -0.589001  1.117814 -2.421802
D  0.188695 -0.758872 -0.933237  0.955057 -1.888294  0.226434
E  0.190794  1.978757  2.605967  0.683509  1.922458  0.228953

In [34]:
df.loc['A']

W      2.706850
X      0.628133
Y      0.907969
Z      0.503826
new    0.404144
sal    3.248220
Name: A, dtype: float64

In [35]:
df.iloc[2]

W     -2.018168
X      0.740122
Y      0.528813
Z     -0.589001
new    1.117814
sal   -2.421802
Name: C, dtype: float64

In [36]:
df.loc['A','Z']

0.5038257538223936

In [38]:
df.loc[['A','C'],['W','Y']]

W         Y
A  2.706850  0.907969
C -2.018168  0.528813

In [39]:
df[:2]

W         X         Y         Z       new       sal
A  2.706850  0.628133  0.907969  0.503826  0.404144  3.248220
B  0.651118 -0.319318 -0.848077  0.605965 -1.454042  0.781342

In [44]:
df.iloc[:3,:2]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122

In [45]:
df>0

W      X      Y      Z    new    sal
A   True   True   True   True   True   True
B   True  False  False   True  False   True
C  False   True   True  False   True  False
D   True  False  False   True  False   True
E   True   True   True   True   True   True

In [46]:
df[df>0]

W         X         Y         Z       new       sal
A  2.706850  0.628133  0.907969  0.503826  0.404144  3.248220
B  0.651118       NaN       NaN  0.605965       NaN  0.781342
C       NaN  0.740122  0.528813       NaN  1.117814       NaN
D  0.188695       NaN       NaN  0.955057       NaN  0.226434
E  0.190794  1.978757  2.605967  0.683509  1.922458  0.228953

In [49]:
df[df['W']>df['Y']]

W         X         Y         Z       new       sal
A  2.706850  0.628133  0.907969  0.503826  0.404144  3.248220
B  0.651118 -0.319318 -0.848077  0.605965 -1.454042  0.781342
D  0.188695 -0.758872 -0.933237  0.955057 -1.888294  0.226434

In [50]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [53]:
df[(df['W']>0) & (df['X']<df['Y'])]

W         X         Y         Z       new       sal
A  2.706850  0.628133  0.907969  0.503826  0.404144  3.248220
E  0.190794  1.978757  2.605967  0.683509  1.922458  0.228953

In [54]:
df[(df['W']>0) | (df['X']<df['Y'])]

W         X         Y         Z       new       sal
A  2.706850  0.628133  0.907969  0.503826  0.404144  3.248220
B  0.651118 -0.319318 -0.848077  0.605965 -1.454042  0.781342
D  0.188695 -0.758872 -0.933237  0.955057 -1.888294  0.226434
E  0.190794  1.978757  2.605967  0.683509  1.922458  0.228953

In [58]:
countrynames='CA NY WY OR CO'.split()
countrynames

['CA', 'NY', 'WY', 'OR', 'CO']

In [59]:
df['States']=countrynames

In [60]:
df

W         X         Y         Z       new       sal States
A  2.706850  0.628133  0.907969  0.503826  0.404144  3.248220     CA
B  0.651118 -0.319318 -0.848077  0.605965 -1.454042  0.781342     NY
C -2.018168  0.740122  0.528813 -0.589001  1.117814 -2.421802     WY
D  0.188695 -0.758872 -0.933237  0.955057 -1.888294  0.226434     OR
E  0.190794  1.978757  2.605967  0.683509  1.922458  0.228953     CO

In [61]:
#reset to default 0,1..n index
df.reset_index()

index         W         X         Y         Z       new       sal States
0     A  2.706850  0.628133  0.907969  0.503826  0.404144  3.248220     CA
1     B  0.651118 -0.319318 -0.848077  0.605965 -1.454042  0.781342     NY
2     C -2.018168  0.740122  0.528813 -0.589001  1.117814 -2.421802     WY
3     D  0.188695 -0.758872 -0.933237  0.955057 -1.888294  0.226434     OR
4     E  0.190794  1.978757  2.605967  0.683509  1.922458  0.228953     CO

In [62]:
df.set_index('States')

W         X         Y         Z       new       sal
States                                                            
CA      2.706850  0.628133  0.907969  0.503826  0.404144  3.248220
NY      0.651118 -0.319318 -0.848077  0.605965 -1.454042  0.781342
WY     -2.018168  0.740122  0.528813 -0.589001  1.117814 -2.421802
OR      0.188695 -0.758872 -0.933237  0.955057 -1.888294  0.226434
CO      0.190794  1.978757  2.605967  0.683509  1.922458  0.228953

In [63]:
df.set_index('States',inplace=True)

In [64]:
df

W         X         Y         Z       new       sal
States                                                            
CA      2.706850  0.628133  0.907969  0.503826  0.404144  3.248220
NY      0.651118 -0.319318 -0.848077  0.605965 -1.454042  0.781342
WY     -2.018168  0.740122  0.528813 -0.589001  1.117814 -2.421802
OR      0.188695 -0.758872 -0.933237  0.955057 -1.888294  0.226434
CO      0.190794  1.978757  2.605967  0.683509  1.922458  0.228953

In [73]:
#MULTIDIMENSIONAL ARRAY

In [65]:
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [66]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [67]:
df=pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1  2.706850  0.628133
   2  0.907969  0.503826
   3  0.651118 -0.319318
G2 1 -0.848077  0.605965
   2 -2.018168  0.740122
   3  0.528813 -0.589001

In [68]:
df.loc['G1']

A         B
1  2.706850  0.628133
2  0.907969  0.503826
3  0.651118 -0.319318

In [71]:
df.loc['G1'].loc[1]

A    2.706850
B    0.628133
Name: 1, dtype: float64

In [72]:
df.index.names

FrozenList([None, None])

GROUP BY

In [82]:
#Create dataframe

data={'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
      'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [83]:
df=pd.DataFrame(data)

In [84]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [85]:
df1=df.groupby("Company")

In [86]:
df1.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [87]:
df1

In [88]:
df1.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [96]:
df1.describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [97]:
df.describe()

Sales
count    6.000000
mean   229.500000
std    100.899455
min    120.000000
25%    143.000000
50%    221.500000
75%    315.750000
max    350.000000

In [98]:
df.describe().transpose()

count   mean         std    min    25%    50%     75%    max
Sales    6.0  229.5  100.899455  120.0  143.0  221.5  315.75  350.0

In [100]:
df1.describe().transpose()['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

#MERGING,JOINING AND CONCANTENATING

In [103]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                 'B':['B0','B1','B2','B3'],
                 'C':['C0','C1','C2','C3'],
                 'D':['D0','D1','D2','D3']},
                index=[0,1,2,3])

In [104]:
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                 'B':['B4','B5','B6','B7'],
                 'C':['C4','C5','C6','C7'],
                 'D':['D4','D5','D6','D7']},
                index=[4,5,6,7])

In [105]:
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
                 'B':['B8','B9','B10','B11'],
                 'C':['C8','C9','C10','C11'],
                 'D':['D8','D9','D10','D11']},
                index=[8,9,10,11])

In [106]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [107]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [108]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [109]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [110]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [111]:
pd.concat([df1,df2,df3],axis=0)

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
#Merge and Join

In [123]:
df4=pd.DataFrame({'A':['A4','A5','A6','A7'],
                  'B':['B0','B0','B1','B1'],
                 'CC':['C4','C5','C6','C7'],
                 'DD':['D4','D5','D6','D7']},
                index=[4,5,6,7])
df4

A   B  CC  DD
4  A4  B0  C4  D4
5  A5  B0  C5  D5
6  A6  B1  C6  D6
7  A7  B1  C7  D7

In [124]:
pd.merge(df2,df4,how='inner',on='A')

A B_x   C   D B_y  CC  DD
0  A4  B4  C4  D4  B0  C4  D4
1  A5  B5  C5  D5  B0  C5  D5
2  A6  B6  C6  D6  B1  C6  D6
3  A7  B7  C7  D7  B1  C7  D7

In [125]:
pd.merge(df2,df4,how='inner',on=['A','B'])

Empty DataFrame
Columns: [A, B, C, D, CC, DD]
Index: []

In [126]:
pd.merge(df2,df4,how='left',on=['A','B'])

A   B   C   D   CC   DD
0  A4  B4  C4  D4  NaN  NaN
1  A5  B5  C5  D5  NaN  NaN
2  A6  B6  C6  D6  NaN  NaN
3  A7  B7  C7  D7  NaN  NaN

In [127]:
pd.merge(df2,df4,how='right',on=['A','B'])

A   B    C    D  CC  DD
0  A4  B0  NaN  NaN  C4  D4
1  A5  B0  NaN  NaN  C5  D5
2  A6  B1  NaN  NaN  C6  D6
3  A7  B1  NaN  NaN  C7  D7

In [128]:
pd.merge(df2,df4,how='outer',on=['A','B'])

A   B    C    D   CC   DD
0  A4  B4   C4   D4  NaN  NaN
1  A5  B5   C5   D5  NaN  NaN
2  A6  B6   C6   D6  NaN  NaN
3  A7  B7   C7   D7  NaN  NaN
4  A4  B0  NaN  NaN   C4   D4
5  A5  B0  NaN  NaN   C5   D5
6  A6  B1  NaN  NaN   C6   D6
7  A7  B1  NaN  NaN   C7   D7

In [132]:
left=pd.DataFrame({'A':['a1','a2','a3'],
                  'B':['b1','b2','b3'],
                  'C':['c1','c2','c3'],
                  'key':['k1','k2','k3']})

In [140]:
right=pd.DataFrame({'D':['a1','a2','a3'],
                  'E':['b1','b2','b3'],
                   'key1':['k1','k2','k3']})

In [141]:
left.join(right)

A   B   C key   D   E key1
0  a1  b1  c1  k1  a1  b1   k1
1  a2  b2  c2  k2  a2  b2   k2
2  a3  b3  c3  k3  a3  b3   k3

In [142]:
# unique  -->distinct values  -- distinct 
# nunique --> number of unique values -- count(distinct)
# value_count  -->  groupby(count(distinct))

In [145]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [148]:
#Apply functions :

def times2(x):
    return x*2
df['Sales'].apply(times2)

0    400
1    240
2    680
3    248
4    486
5    700
Name: Sales, dtype: int64

In [149]:
# SORTING AND ORDERING
df.sort_values(by='Person')

Company   Person  Sales
2    MSFT      Amy    340
4      FB     Carl    243
1    GOOG  Charlie    120
0    GOOG      Sam    200
5      FB    Sarah    350
3    MSFT  Vanessa    124

In [150]:
df.sort_values(by='Sales')

Company   Person  Sales
1    GOOG  Charlie    120
3    MSFT  Vanessa    124
0    GOOG      Sam    200
4      FB     Carl    243
2    MSFT      Amy    340
5      FB    Sarah    350

In [151]:
# Drop rows with Null values (NaN values)
#  df.dropna()

# Replace Nan values with something else

# df.fillna('FILL')

# DATA_INPUT AND OUTPUT

In [154]:
df=pd.read_excel('Excel_Sample.xlsx')

In [155]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [156]:
df2=pd.read_csv('example')

In [157]:
df2

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [161]:
df=pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

In [164]:
df2.to_csv('example_res',index='False')

In [167]:
df.to_excel('Excel_Sample_out.xlsx',index=False)

In [18]:
import pandas as pd

In [19]:
movie_data=pd.read_csv('u.user',delimiter='|')

In [20]:
movie_data

1  24  M     technician  85711
0      2  53  F          other  94043
1      3  23  M         writer  32067
2      4  24  M     technician  43537
3      5  33  F          other  15213
4      6  42  M      executive  98101
5      7  57  M  administrator  91344
6      8  36  M  administrator  05201
7      9  29  M        student  01002
8     10  53  M         lawyer  90703
9     11  39  F          other  30329
10    12  28  F          other  06405
11    13  47  M       educator  29206
12    14  45  M      scientist  55106
13    15  49  F       educator  97301
14    16  21  M  entertainment  10309
15    17  30  M     programmer  06355
16    18  35  F          other  37212
17    19  40  M      librarian  02138
18    20  42  F      homemaker  95660
19    21  26  M         writer  30068
20    22  25  M         writer  40206
21    23  30  F         artist  48197
22    24  21  F         artist  94533
23    25  39  M       engineer  55107
24    26  49  M       engineer  21044
25    27  40  F      librarian  30030
26    28  32  M         writer  55369
27    29  41  M     programmer  94043
28    30   7  M        student  55436
29    31  24  M         artist  10003
..   ...  .. ..            ...    ...
912  914  44  F          other  08105
913  915  50  M  entertainment  60614
914  916  27  M       engineer  N2L5N
915  917  22  F        student  20006
916  918  40  M      scientist  70116
917  919  25  M          other  14216
918  920  30  F         artist  90008
919  921  20  F        student  98801
920  922  29  F  administrator  21114
921  923  21  M        student  E2E3R
922  924  29  M          other  11753
923  925  18  F       salesman  49036
924  926  49  M  entertainment  01701
925  927  23  M     programmer  55428
926  928  21  M        student  55408
927  929  44  M      scientist  53711
928  930  28  F      scientist  07310
929  931  60  M       educator  33556
930  932  58  M       educator  06437
931  933  28  M        student  48105
932  934  61  M       engineer  22902
933  935  42  M         doctor  66221
934  936  24  M          other  32789
935  937  48  M       educator  98072
936  938  38  F     technician  55038
937  939  26  F        student  33319
938  940  32  M  administrator  02215
939  941  20  M        student  97229
940  942  48  F      librarian  78209
941  943  22  M        student  77841

[942 rows x 5 columns]